### ISSUE TITLE
MAJOR! CRASHING WHEN LEAVING.

### ISSUE THREAD

**Issue by keenan1127** [LtxProgrammer/Changed-Minecraft-Mod#101]
for some reason, when I leave the game, it crashes. instantly.
I've heard this is because of my special form, but idk.

**Comment by LtxProgrammer** [comment]
If you can recreate this, please reopen with a crash log.

**Comment by keenan1127** [comment]
I can't, Quinn has the logs and he won't respond.

**Comment by LtxProgrammer** [comment]
The Minecraft client should spit out some logs whenever you crash. Quinn isn't involved in this, unless the whole server is crashing.
