### ISSUE TITLE
Head disappearing when transfurred

### ISSUE THREAD

**Issue by AbsoluteJuicer** [LtxProgrammer/Changed-Minecraft-Mod#1014]
Changed Version: 0.13.1
Changed Addon Version: 2.5.8
Config: UsingNewModels = False

Player Head and mod head will disappear when transfurred by Manta Ray Male/Female and Crocodile, while remains normal when transfurred by Shark and Tiger Shark mobs. I was suspecting First Person Models mod, but testing with only changed and first person models didn't reenact the bug. I also checked both latest and debug logs, but nothing is found, and no errors being thrown. Could it be the head rendering system not being compatible with the older models? I really liked the old models, but I really couldn't find the culprit mod in my modpack.

**Comment by LtxProgrammer** [comment]
Could you describe how this error happened?
Is it on your own transfurred player model?
Is it on NPC entity models?

The head visibility is updated every time the model is prepped to render, I suspect it would be one of your mods. What is in your modpack?

**Comment by AbsoluteJuicer** [comment]
I suspect it's caused by First Person Models mod since this mod got mentioned in the other thread of the same issue #1016  

More specifically:
->before TF, both my player head and NPC head existed, and rendered correctly
->after TF, my head and NPC head (of the same variant) disappeared
(This problem only occurred on variants with old models) 

I have also tested with only Changed mod and it was not the issue.

**Comment by Park1423** [comment]
I've been using first person model for a while now and have seen no issues. I think your problem lies elsewhere.

**Comment by LtxProgrammer** [comment]
Moved to #1182
