### ISSUE TITLE
This... 1

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1019]
Although I have modified this module, the original version of the module can also cause the same bug.

BUG:

https://github.com/user-attachments/assets/f16b6d00-7a58-46df-a123-831ae5cebfb4

NaN:

https://github.com/user-attachments/assets/d21b2c49-536f-4d0e-bd3c-9f3d06c380d8

**Comment by cecnull1** [comment]
这不死图腾音效触发时间还与我播放的音乐正好卡上时间点了

It seems that the trigger time of the totem sound effect is just synchronized with the time point of the music I'm playing.

**Comment by LtxProgrammer** [comment]
This issue resembles the original totem of undying bug. Maybe I could find a more universal solution.

**Comment by cecnull1** [comment]
Do you know what is causing this issue?
