### ISSUE TITLE
This... 2

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1022]
[crash-2024-09-08_16.13.21-client.txt](https://github.com/user-attachments/files/16921425/crash-2024-09-08_16.13.21-client.txt)

https://github.com/user-attachments/assets/6ebb3612-b7f9-4d05-b42e-b105c02c698b

**Comment by LtxProgrammer** [comment]
Can you please provide the whole crash log? What mods did you have installed?
