### ISSUE TITLE
Dark Latex Wolves Not Spawning.

### ISSUE THREAD

**Issue by TheBreadMan1** [LtxProgrammer/Changed-Minecraft-Mod#1030]
The title isn't entirely true. They do spawn, very-very-very rarely. Like, I'm in the Dark Latex biome and for as far as the eye can see there are Latex Pups but not a single normal male or female wolf. Is anyone else having this issue? I searched for hours and only ever managed to stumble across one on the outskirts of the biome.

**Comment by Pashavgp** [comment]
Shouldn't it be like this?

**Comment by TheBreadMan1** [comment]
It could be an intentional chose by the developer but I'm not really sure. It doesn't make sense for the white latex guys to have both Pure White Wolves and Headless Knights defending their biome but the black latex only have the pups. Wouldn't it make more sense for both sides to have a bipedal and quadrapedal creature spawning frequently?

**Comment by LtxProgrammer** [comment]
Reworked spawning, to also now intentionally spawn variety of dark latex entities.
