### ISSUE TITLE
Some mod overwrites ModelPart render code such that Changed can't create a mixin.

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1036]
https://github.com/user-attachments/assets/3509d01f-be96-4248-ba72-4d10b1e20735

[crash-2024-09-15_10.12.37-client.txt](https://github.com/user-attachments/files/17004402/crash-2024-09-15_10.12.37-client.txt)

**Comment by LtxProgrammer** [comment]
`org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @WrapWithCondition annotation on orCapture could not find any targets matching 'render(Lnet/minecraft/world/entity/LivingEntity;FFLcom/mojang/blaze3d/vertex/PoseStack;Lnet/minecraft/client/renderer/MultiBufferSource;I)V' in net.minecraft.client.renderer.entity.LivingEntityRenderer.`

**Comment by gengyoubo** [comment]
Would it be possible to prioritize the loading of this mod to solve this problem?

**Comment by gengyoubo** [comment]
Or would reflecting on oculus or modifying the oculus code with mixin solve the problem?

**Comment by LtxProgrammer** [comment]
The `WrapWithCondition` mixin was replaced with `Inject` mixins to prepare layers for visibility.

**Comment by LtxProgrammer** [comment]
637d869e12f4eaead3fc6ff6e3718a960eb1a824
