### ISSUE TITLE
Ferritecore crashes LatexCoveredBlocks model bake event.

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1038]
[错误报告-2024-9-15_15.36.27.zip](https://github.com/user-attachments/files/17004958/-2024-9-15_15.36.27.zip)

By 帅气小彪彪

**Comment by cecnull1** [comment]
Did I ask the wrong question?

**Comment by LtxProgrammer** [comment]
> Did I ask the wrong question?

I'm not at my computer right now, so I can't diagnose the attached file right now.

**Comment by cecnull1** [comment]
> 不要把整合包的毛病发给changed模组的作者，好吗？ @cecnull1

为了增强兼容性而特意报告（）

**Comment by LtxProgrammer** [comment]
```
java.lang.RuntimeException: Unknown property 'bottom' on 'Block{alloyed:steel_catwalk}'
	at malte0811.ferritecore.impl.KeyValueConditionImpl.getPredicate(KeyValueConditionImpl.java:31) ~[ferritecore-4.2.2-forge.jar%2396!/:4.2.2]
```

**Comment by LtxProgrammer** [comment]
Error is thrown at [KeyValueConditionImpl.java:31](https://github.com/malte0811/FerriteCore/blob/0bd73c6efb8efe6a4460894a978de96fa9ac4266/Common/src/main/java/malte0811/ferritecore/impl/KeyValueConditionImpl.java#L31)
