### ISSUE TITLE
Player is not hidden in tall box, and can "double enter"

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1039]
https://github.com/user-attachments/assets/b147f3f0-ede1-44c3-ae6f-788ef424ed56

![d113cded3ac37eac1e10ec808893cc88](https://github.com/user-attachments/assets/cb98c93a-91ce-4545-a96d-e29ead321a0c)

![ee454fb4525ad159b36eb2cdd3575595](https://github.com/user-attachments/assets/7027d9ed-b9d3-46ed-9a28-a2e66df8987c)

**Comment by cecnull1** [comment]
There are two bugs here. 1. If you are already inside the box, right-clicking the box again will cause a logic error. 2. The developer mentioned that the model was not successfully hidden.

**Comment by LtxProgrammer** [comment]
After reviewing the code, 27cb6b75 broke properly hiding the player with a misconfiguration.
