### ISSUE TITLE
Idea: New customizable hairstyles

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1044]
**Low priority! **
This can be a hassle to work, so make sure the necessary stuff is finished before do it.

(The content used machine translation.)
1.Drawing of hairstyle patterns
    For example, place a 32x16 flattened texture image in .minecraft/config/changed/, you can draw your hairstyle in the same way you would draw a Minecraft skin, and then fill the hairstyle part with pure white/black (no texture painting required).

2.Roughly implement the idea
    The basic texture of each gum animal's hairstyle is drawn according to its characteristics and filled in a 32x16 flattened diagram so that it can be later cropped using the drawn hairstyle pattern.
    Then reading the custom hairstyle file, according to the hairstyle pattern, the corresponding part is cut out from the basic hair texture of the beasts and used as the hair that is actually displayed.
    Finally, apply the hair to the model of the beast, and it is completed.

I'm sorry that I don't know anything about developing mods, so I can't provide an example to demonstrate.

**Comment by XiaoTDM** [comment]
Since the hairstyle function was removed due to the remodel, if it can be brought back, I hope to use the highly customizable hairstyle that I described.

**Comment by LtxProgrammer** [comment]
Custom hairstyles were removed due to the complications they posed with models having unique hair (e.g: the siren). Having users have their own hairstyle presents a challenge on how it would sync between clients.
