### ISSUE TITLE
Compatibility with "Origins (Forge)" module 2

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1045]
In this module, after undergoing beastification, certain functions from the Origin module are missing. One of these is that when using the phasing ability from the Phantom race in the Origin module, once you use the beastification feature of this module, it results in taking damage while phasing through walls, instead of being immune to damage as intended.

https://github.com/user-attachments/assets/5217ad5d-503c-4fae-bbc1-7e46264e23a1

**Comment by gengyoubo** [comment]
你有和origin模组去提交这个问题吗？

**Comment by cecnull1** [comment]
没有

**Comment by gengyoubo** [comment]
真的应该写点啥来限制TF（当然，如果要是要加个混合模组也不是不行）

**Comment by gengyoubo** [comment]
# 我懂了
### 这都是游戏特性，如果你把它修了那就变成bug了！

**Comment by gengyoubo** [comment]
# 这都是游戏特性不是~~BUG!~~

**Comment by Foxyas** [comment]
Maybe a Small Compatibility to start like a TransfurVariant would be cool but someone could just Set they own Variant For any in the start of the game With cheats on so =/

**Comment by cecnull1** [comment]
但不代表未来会发生

**Comment by gengyoubo** [comment]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/pull/1142

**Comment by gengyoubo** [comment]
反向似乎行不通，应该没有人那么极端！

**Comment by cecnull1** [comment]
**origin指令** 是寂寞吗？
首先，改回人类
然后，兽化
然后，再改成其他起源

**Comment by gengyoubo** [comment]
对

**Comment by gengyoubo** [comment]
![屏幕截图 2024-11-06 175254](https://github.com/user-attachments/assets/be9dc315-1fee-4571-82e3-b100b6097bdf)
Note: After installing Lithium, phantom players will take asphyxiation damage when inside a solid cube, this is a bug, the workaround can be found at the bottom of the main module page.

**Comment by gengyoubo** [comment]
The Phantoms' phase shift conflicts with Lithium, causing the player to suffocate inside the cube. This can be resolved by modifying the lithium configuration file lithium.properties by adding mixin.entity.collisions.suffocation=false to the last line.

**Comment by gengyoubo** [comment]
@LtxProgrammer I think this bug has been resolved

**Comment by gengyoubo** [comment]
> ![屏幕截图 2024-11-06 175254](https://private-user-images.githubusercontent.com/113955003/383476337-be9dc315-1fee-4571-82e3-b100b6097bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODM1MjMsIm5iZiI6MTczMDg4MzIyMywicGF0aCI6Ii8xMTM5NTUwMDMvMzgzNDc2MzM3LWJlOWRjMzE1LTFmZWUtNDU3MS04MmUzLWIxMDBiNjA5N2JkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwODUzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmMwZjM3ZGU5MmFhZDFhZmE5OTRlMjNjMjljNmY2YzQ4ZmJkYmJiM2JlNWM1MmRmNjE1Zjg1YTA4NTU2Y2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9WKOUb6Wa2Ho-1UsPSFmLzViNDpzBCsZKHYRwPrTfYU) Note: After installing Lithium, phantom players will take asphyxiation damage when inside a solid cube, this is a bug, the workaround can be found at the bottom of the main module page.

The origin of the fabric version is this

**Comment by gengyoubo** [comment]
https://github.com/apace100/origins-fabric/issues/473

**Comment by gengyoubo** [comment]
If it's forge it's rubidium-mixins.properties

**Comment by gengyoubo** [comment]
@LtxProgrammer you can close this issue!

**Comment by cecnull1** [comment]
不止这一个，发现：如果起源中，其特性有“在水下重力表现跟地面相同”，那么该模组中的水生生物进入水中时，会因为被设置为“无重力”而发生问题

**Comment by gengyoubo** [comment]
没加changed也这样吗？

**Comment by cecnull1** [comment]
我改一下话

**Comment by cecnull1** [comment]
> 没加changed也这样吗？

只要设置为“无重力”，就会出现该类问题，之所以说他BUG……
# 谁家好人水下胶兽不能游泳啊？

**Comment by gengyoubo** [comment]
啥问题？

**Comment by cecnull1** [comment]
如果水下胶兽钻进水里，无重力属性会被打开，然而在起源中把水对玩家的影响去除掉了（除了窒息），导致无法正常落地，也无法游泳

**Comment by gengyoubo** [comment]
哪个起源？

**Comment by cecnull1** [comment]
> 哪个起源？

附属模组中的
