### ISSUE TITLE
Start: 100% CPU and >80% RAM

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1047]
![594bb5581d1a3137a44d068a593d9fc5](https://github.com/user-attachments/assets/a90a7d19-1162-4aaa-bc4b-8e5bcbe3478a)

Modpack Name: Creative Drawers Producer

Additional Mods: Changed

Mods Removed: Oculus, FerriteCore

Developer, can you find better ways to optimize performance?

**Comment by cecnull1** [comment]
![e72c97fcb4ca4912e57fe07a66a85029](https://github.com/user-attachments/assets/f8331025-a2a9-462b-94a1-7b1f90b0108d)

Wonderful CPU Utilization Graph

**Comment by gengyoubo** [comment]
开发人员：你食不食油饼

**Comment by cecnull1** [comment]
@gengyoubo 你咋来了（）

**Comment by cecnull1** [comment]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/issues/1041

**Comment by spacedan228** [comment]
isn't it a minecraft or some other mod's issue

**Comment by LtxProgrammer** [comment]
100% CPU utilization is not an issue, and is rather a good thing. As for memory, that can be expected with a large mod pack with limited performance mods. Please make sure you have `changed-client.toml` configured properly.

**Comment by cecnull1** [comment]
Forgot about this configuration file, let me adjust it in a moment.
