### ISSUE TITLE
Suit mode fails on remote player.

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1048]
https://github.com/user-attachments/assets/8b78476d-d872-4b4d-87b2-ba6f1fde9728

**Comment by cecnull1** [comment]
https://github.com/user-attachments/assets/71bc8158-b3b9-437c-a959-a8fc4b522f6e

**Comment by cecnull1** [comment]
It appears that it only occurs in the revised version, so you might as well consider this issue a non-issue, like air.

**Comment by cecnull1** [comment]
Based on multiple experiments, it was found that the module has bugs, regardless of whether or not it has been modified.

**Comment by gengyoubo** [comment]
输掉所有，或者是赢下所有[doge]

**Comment by LtxProgrammer** [comment]
Does not happen in current Github version.
