### ISSUE TITLE
Player Head Position breaks if player is untransfured during transfur animation

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1065]
Will stay like this across worlds/servers until client restart.

https://github.com/user-attachments/assets/b0951d9e-2539-4714-9020-3840c8b07042

![image](https://github.com/user-attachments/assets/c938947c-ef96-489c-8e61-88c26dc854ed)

**Comment by gengyoubo** [comment]
Is forcibly interrupting an animation with a command considered a bug?

**Comment by Y1rd** [comment]
> Is forcibly interrupting an animation with a command considered a bug?

Might be useful to fix because the same problem would happen if it was interrupted by something else...

**Comment by gengyoubo** [comment]
That means there are other ways to interrupt the TF animation besides commands?

**Comment by gengyoubo** [comment]
That means there are other ways to interrupt the TF animation besides commands?

**Comment by gengyoubo** [comment]
I think we should think about whether it's a bug when the TF animation is interrupted by certain events?

**Comment by Y1rd** [comment]
> That means there are other ways to interrupt the TF animation besides commands?

Probably, taking account of the many mods you can install. Better to fix it.

**Comment by gengyoubo** [comment]
I'm thinking if the animation is interrupted would there be a bug other than having to re-TF? If not I'd suggest treating this as a game feature.

**Comment by LtxProgrammer** [comment]
The vanilla player renderer does not set the head's z-rotation each frame. The animation can set the head's rotation, but doesn't reset it if the animation ends abruptly.

**Comment by gengyoubo** [comment]
I was wondering if it would be possible to write a code like this: first save the values of the player before starting the TF animation at the very beginning, and when the animation is interrupted by unusual means, it will refer to the previously saved values.
