### ISSUE TITLE
Allow the Danger Meter to have a custom screen position

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1066]
Kinda like those custom clients (Lunar) which allow you to move modules filled with information around.
It's a little hard to peek at the bottom left corner to check your danger, especially if you have a ultra wide monitor.

**Comment by Foxyas** [comment]
A Client Configuration For change the X and Y of the Overlay [Or even a "grab and drag" system] for any location of the screen sounds like a good feature
