### ISSUE TITLE
Document How Pale Works

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1076]
Honestly, there isn't any information anywhere about how the pale virus works when enabling the game rule. Unless you dive into the code.

**Comment by Y1rd** [comment]
Could also use this as a chance to rework it a little, or add visual indicators for it. Might make it much better to play with on.

**Comment by Y1rd** [comment]
> Could also use this as a chance to rework it a little, or add visual indicators for it. Might make it much better to play with on.

On second note, the commands don't have an output either.

**Comment by spacedan228** [comment]
pale is supposed to have stages, with dealing more damage on later stages, but for some reason it doesn't work like that, only starting to rapidly deal damage in the final stage

**Comment by Y1rd** [comment]
> pale is supposed to have stages, with dealing more damage on later stages, but for some reason it doesn't work like that, only starting to rapidly deal damage on the final stage

Might just straight up be broken, then.

**Comment by LtxProgrammer** [comment]
I had a plan to rework computers, such that they actually work as desktops and that players can find drives around facilities with information/pictures/recipes. I think this can be documented in one of these drives.

**Comment by Y1rd** [comment]
> I had a plan to rework computers, such that they actually work as desktops and that players can find drives around facilities with information/pictures/recipes. I think this can be documented in one of these drives.

I've now documented Pale onto the wiki [here](https://changedmc.miraheze.org/wiki/Mechanics). Unsure if this issue should stay open regarding documenting it in-game. I'll close it for now.

**Comment by LtxProgrammer** [comment]
> I've now documented Pale onto the wiki [here](https://changedmc.miraheze.org/wiki/Mechanics). Unsure if this issue should stay open regarding documenting it in-game. I'll close it for now.

I want to have some information on pale written with the computer update, but this doesn't need to be reopened for that.
