### ISSUE TITLE
Unable to grant advancements through commands

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1080]
You can only grant yourself the hints to crafting recipes.
![image](https://github.com/user-attachments/assets/22338015-8ef9-4130-888b-9809a8f1277e)

**Comment by Foxyas** [comment]
Try use minecraft:changed/etc

**Comment by Y1rd** [comment]
> Try use minecraft:changed/etc

![image](https://github.com/user-attachments/assets/3cc4870f-8556-4933-bbbb-abacaaffa4c1)
Huh, they are under the minecraft root instead. Odd.
