### ISSUE TITLE
> #1056

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1081]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/issues/1056

咱这里聊Issue #1056

Let's discuss Issue #1056 here.

If the issue has been resolved, please have the developer close this Issue.

**Comment by cecnull1** [comment]
#1068

**Comment by Y1rd** [comment]
Perhaps this should be revisited actually, due to the performance cost of constantly changing attributes.

**Comment by cecnull1** [comment]
Indeed, it should be reconsidered.

**Comment by cecnull1** [comment]
> > Nor is it suitable. This kind of operation can be said to be redundant. I think for a mod that is going to get bigger and bigger in the future, use all these operations where they are really needed, rather than looping here...
> > This mechanism itself is a design mistake and can result in wasted performance (even if the impact is really small).
> > 也不合适。这种可以说属于多余的运算。我认为对于一个未来体量会越来越大的mod，把这些运算都用到真正需要的地方，而不是在这里循环执行... 这种机制本身就是设计失误，会造成性能浪费（哪怕影响真的很小）。
> 
> How do you think it should be set?

@gengyoubo  我认为用属性修饰符挺好的，能避免兼容性问题。

I think using attribute modifiers is quite good, as it can avoid compatibility issues.
