### ISSUE TITLE
Carpet is messed up in old structures

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1086]
![image](https://github.com/user-attachments/assets/bdf376c0-9d4e-48f4-8dbc-9eb65581a6f4)

**Comment by cecnull1** [comment]
我见过这个BUG，但是我把他当做正常设计了

**Comment by bijimio** [comment]
im not 100% sure, however the old lab structures may be removed in exchange for new facility pieces
