### ISSUE TITLE
Allow latex to "forgive" players for a few seconds after transfur

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1090]
_I was playing some night time survival and I thought about this (because it happened to me):_
While fighting latex, if the player gets transfurred, they might hit the latex they were fighting after they get transfurred. Resulting in that latex fighting them again, dealing damage now.
Perhaps allow for nearby latex to forgive the player for a few seconds after transfur, so that if the player doesn't want to kill the latex in question, it doesn't accidentally attack them.

**Comment by LtxProgrammer** [comment]
Added in ae27d4a529652607a18f62d4ad1d03166ba8a822 (In a way)
