### ISSUE TITLE
How to load mxin?

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#1106]
As you know, there are two technical issues in version 0.13.1
One is the problem with #888, which only shows the localized key for ability.changed.switch_transfur_mode.selec, and the subsequent modes are always in English (i.e. hardcoded).
The other is a layer issue with #943. How can I use mixin to change the code here?

**Comment by gengyoubo** [comment]
Similar to patching a module.

**Comment by LtxProgrammer** [comment]
These are not issues prevalent in the GitHub version of the mod. Please don't create issues that are just asking how to do something.

**Comment by gengyoubo** [comment]
#888 is solved
