### ISSUE TITLE
Null Tags Logs Every 5 minutes 

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#1107]
Every 5 mins a Log is Send with the erro

`[Server thread/ERROR] [ne.lt.ch.Changed/]: Null tag encountered while updating tag for PLAYER`
![image](https://github.com/user-attachments/assets/6403fc40-164d-47b4-b039-37b05e0cb6a6)

Is not a Fatal Erro but is kinda anoying after some time

**Comment by Foxyas** [comment]
The server was with Changed mod 0.14 and with no players online btw

**Comment by LtxProgrammer** [comment]
I had left this in to debug the Changed DFU, since I was getting null pointer exceptions. The log itself doesn't mean anything. At the time I thought having a null tag was an error state, but it doesn't seem that way.
