### ISSUE TITLE
Suggestions for Mods 1 (Minecraft Commands)

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1113]
对于命令系统来说，给execute添加几个判断，和几个新指令是很好的选择，有助于数据包的开发（并且会提高可移植性）。

1. 获取某位玩家当前的胶兽形态
2. 允许untf/untransfur指令的参数为空，这种情况下默认为执行者
3. progresstransfur指令中，胶兽形态放在最后并作为可选值（留空则选择上一次被兽化攻击时的类型），<progression>放在胶兽形态之前。此外，<progression>允许负值以便退兽化进度，（可能破坏向后兼容性）
4. 有时需要全部对选定的玩家进行群体兽化/解除，/untf（或untransfur）、/transfur（或/tf）、/progresstransfur允许多玩家实体选择。
5. 在execute中，if/unless允许 判断某个玩家是否是某个胶兽形态
6. 允许通过特定指令，使得胶兽玩家强制抓住某个人形生物（可不实现）
还有其他想法（会在评论中一一补充）

For the command system, adding a few conditions to `execute` and introducing a few new commands would be a great choice, which would aid in the development of datapacks (and enhance portability).

- [x] 1. Retrieve the current slime form of a specific player.
- [x] 2. Allow the `untf`/`untransfur` command to have an empty parameter, in which case it defaults to the executor.
- [x] 3. In the `progresstransfur` command, place the slime form at the end as an optional value (if left blank, it selects the type from the last time the player was attacked by a beast), with `<progression>` placed before the slime form. Additionally, `<progression>` allows negative values to regress the transformation progress. (may break backward compatibility)
- [x] 4. Sometimes it is necessary to mass-transform/untransform selected players, `/untf` (or `untransfur`), `/transfur` (or `/tf`), `/progresstransfur` should allow for multi-player entity selection.
- [ ] 5. In `execute`, `if`/`unless` should allow checking if a player is in a specific slime form.
- [ ] 6. Allow a specific command to force a slime player to grab a humanoid creature (implementation not required).

Other ideas will be supplemented one by one in the comments.

**Comment by LtxProgrammer** [comment]
> In the progresstransfur command, place the slime form at the end as an optional value (if left blank, it selects the type from the last time the player was attacked by a beast), with <progression> placed before the slime form.

This is no longer possible, the last attacking variant is not tracked.

**Comment by XiaoTDM** [comment]
只要可以省略匹配对象就足够了，默认执行对象为命令执行者。
但有一说一，/transfur的形态命名空间是有点不方便（指form_前缀无法快速Tab）
It is enough to omit the matching object, and the default execution object is the command executor.
But one thing to say, the form namespaces are a bit inconvenient for executing commands (referring to the fact that form_ prefix can't be quickly tabbed).
