### ISSUE TITLE
A problem with Display Icons

### ISSUE THREAD

**Issue by Dimonaaas** [LtxProgrammer/Changed-Minecraft-Mod#1128]
the problem is that it is enabled, but showing ordinary vanilla minecraft creatures, what do I need to do to fix it?
![AA6E4FD9-27F6-49CC-AA29-5F17F5705D37](https://github.com/user-attachments/assets/53685d0c-e11e-4ef1-a319-fabf888d8a06)

![DB7F5510-502A-4B0A-A7F6-0DBD0EE1EE34](https://github.com/user-attachments/assets/c3e8560d-59df-404e-8987-858705296511)

**Comment by gengyoubo** [comment]
#673
