### ISSUE TITLE
Pale is broken

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1130]
Related to #1076 

Pale does not apply any damage to the player until it's last phase kicks in, rapidly killing the players without warning.
Doesn't seem intended by [looking at the Pale code, which should be applying damage based on pale exposure](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/blob/master/src/main/java/net/ltxprogrammer/changed/process/Pale.java).

**Comment by LtxProgrammer** [comment]
Testing and reviewing the code, I found that the player was being exposed to themself. The modulus used in the code was skipped on on a chance that the exposure was incremented on intervals that never matched it (ex: exposure going from 1199 to 1201, skipping 1200).

**Comment by Y1rd** [comment]
Maybe should add a check to make sure a player isn't exposing to themself. Only to other players.

**Comment by LtxProgrammer** [comment]
Already done
