### ISSUE TITLE
Latex-resistant and Latex-compatible interfaces

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#1133]
For compatibility with certain variants of the module, I think the following could be designed to prevent a bug
# Latex-resistant interfaces
Its main function is to prevent the player from tfing into latex, and when using the command it pops up “A mysterious force is preventing you from becoming latex!”
# Latex-compatible interfaces
When tfing special variants, the original functionality and the post-tf functionality will be preserved.
#
The basic composition of the code can be written like this
```

if(){

}else if(){

}else{

}
```
# 

- [ ] Latex-resistant methods
- [ ] compatibility methods
- [ ] Methods that are neither (generally referring to humans or Latex)

**Comment by gengyoubo** [comment]
This gives you two ways to register, one by yourself and the other by another module.

**Comment by gengyoubo** [comment]
I'll try it first and see if it works. If it doesn't work I'll turn this off.

**Comment by gengyoubo** [comment]
![屏幕截图 2024-11-01 194412](https://github.com/user-attachments/assets/83e7a52b-d9e1-459d-904f-0400358d6a76)

**Comment by gengyoubo** [comment]
https://github.com/gengyoubo/Changed/commit/a311e4dc6ccd20cdd5b908ac28f06a77103f9093

**Comment by gengyoubo** [comment]
What I need to think about is how to write code that is resistant to latexness and compatibility. After writing it could start with a way to put both human and variants outside of latex that can be put in anti-latexability. I'll start writing it when I've gathered enough intel!

**Comment by LtxProgrammer** [comment]
What is the point of this suggestion? Are other mod devs supposed to write implementations to these interfaces? Or is this just extra work on our end?

**Comment by LtxProgrammer** [comment]
> [gengyoubo@a311e4d](https://github.com/gengyoubo/Changed/commit/a311e4dc6ccd20cdd5b908ac28f06a77103f9093)

And why are you doing enum logic with integers, and returning a nullable instead of the mapped optional?

**Comment by gengyoubo** [comment]
> What is the point of this suggestion? Are other mod devs supposed to write implementations to these interfaces? Or is this just extra work on our end?

First of all this can't be considered a suggestion, I'm just going to do this stuff. Secondly in general you don't really need to do compatibility stuff to keep it functional, but once tf after that some bugs happen so I feel the need to fix the bugs!

**Comment by gengyoubo** [comment]
You guys just do the 0.14.1 feature, I just need to get that implemented, I didn't make it mandatory for you to do it, right?

**Comment by LtxProgrammer** [comment]
Then why did you make an "issue"? If there's no problem or suggestion for this project, then there's no need for an issue.
