### ISSUE TITLE
creat don't work!

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#1136]
![屏幕截图 2024-11-01 175957](https://github.com/user-attachments/assets/86a7f910-a323-400d-9ba3-7668d39800d5)
Great module, but makes my mechanical power not work! If normal machinery is covered by the glue at best it's a matter of mapping errors invisibility in place, etc (at least it works) but the train components (including tracks, stations, etc) stick a little bit and the train won't be able to be assembled, it's horrible, I built the train stations on the vinyl plains and didn't realize that when I disassembled them during the modification of the train they were never assembled back together again...

**Comment by LtxProgrammer** [comment]
Tell them to blacklist them in the server config
