### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by GooglieHunter** [LtxProgrammer/Changed-Minecraft-Mod#114]
I got a crash while using the latest version without any other mods (V0.8.2b), it did not make a crash report and the code was -0. I tried to reopen it and my MC was completely gone and I had to reinstall the launcher and everything, I do not know if this is a one time thing or if it can happen at anytime.

**Comment by LtxProgrammer** [comment]
Way too vague. I can't possibly fix a problem nobody has ever encountered before, nor have I encountered myself. I've started up Minecraft hundreds of times with no issues related to corrupting/breaking it.
