### ISSUE TITLE
Suggestion: Remove Raccoons' Blindness

### ISSUE THREAD

**Issue by Anonogon** [LtxProgrammer/Changed-Minecraft-Mod#1149]
The racoon has a great model, but nobody really uses it because of the blindness, which is a real shame. Also, for you lore purists out there that are no doubt wanting to flame me for this, dragonsnow himself said that eyeless forms can see, and there is no implication that the raccoon cannot see. (Dragonsnow quote: https://changed.wiki.gg/wiki/File:ChangedLoreNoEyes.png )

**Comment by XiaoTDM** [comment]
DragonSnow just said they "can see", it doesn't mean that it can see clearly...... Maybe the raccoon can only see vaguely like pure white latex.
Furthermore, raccoons seem to have fused with benign latex, inheriting some of the characteristics of benign latex.
