### ISSUE TITLE
Models underneath the inventory menu

### ISSUE THREAD

**Issue by BlackNinjaReal** [LtxProgrammer/Changed-Minecraft-Mod#1156]
Whenever you in size 4 or auto for menu size, the models of the infected are behind your inventory menu so you can't look at them. When trying to look at the infusers crafting recipes. I don't know if others got the same problem, but still wanted to point it out so it could get fixed.

**Comment by LtxProgrammer** [comment]
Can you provide a screenshot?

**Comment by XiaoTDM** [comment]
Tried to reproduce the issue, here are the results.
However, the window size is already very small at this time, which is an abnormal situation.
![image](https://github.com/user-attachments/assets/ee69c828-aa9f-4a44-9457-76d3696a5e73)

**Comment by BlackNinjaReal** [comment]
sure, I can give an image. Let me get a image of it first.

**Comment by BlackNinjaReal** [comment]
sorry if they look small.
![2024-11-11_19 35 29](https://github.com/user-attachments/assets/21529970-a3d4-496c-96b3-1032afd4f82a)

![2024-11-11_19 35 17](https://github.com/user-attachments/assets/f9357ceb-ece0-42f0-bc37-59572b39c76f)

**Comment by BlackNinjaReal** [comment]
That's what I'm talking about. I'm full screened too btw.

**Comment by LtxProgrammer** [comment]
I'm not able to replicate this issue, what other mods do you have installed?

**Comment by LtxProgrammer** [comment]
Stale; reopen with more information.
