### ISSUE TITLE
Has the white visual filter of pure white latex been removed

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1158]
The white visual filter that existed in old version is gone.

**Comment by LtxProgrammer** [comment]
Is this in the release build or github build?

**Comment by XiaoTDM** [comment]
both of them.

**Comment by Anonogon** [comment]
You are likely experiencing a conflict with another mod, the filter is still present in my game.

**Comment by XiaoTDM** [comment]
> You are likely experiencing a conflict with another mod, the filter is still present in my game.

I haven't add any mod except Changed.

**Comment by XiaoTDM** [comment]
This works well on old version (0.11.3), but not on latest version.
![image](https://github.com/user-attachments/assets/6f2a4033-5e7e-41bf-9f1f-b9f91aefb69b)

**Comment by LtxProgrammer** [comment]
The visual effect is tied to the distortion effects in the accessibility settings. I suspect you have this setting at 0%.

**Comment by LtxProgrammer** [comment]
Please reopen this issue if it persists after you set your distortion effects setting to a value greater than zero.
