### ISSUE TITLE
Why is there no Latex beasts spawning?

### ISSUE THREAD

**Issue by DEE9809** [LtxProgrammer/Changed-Minecraft-Mod#1164]
I tried going on easy mode to normal mode and hard mode but only a few specific latex beasts were spawning...

**Comment by DEE9809** [comment]
I saw the new Changed mod update for Oct. 31th, i checked it out but i saw that no Latex Beasts were spawning in, i only saw the following "Stiger" "Translucent Lizard" "Traffic Cone Dragon" and the aquatic latex beasts, thats the only ones that spwan in, and i tried spanwers, but nothing was spawning

**Comment by DEE9809** [comment]
Was this planned? just making sure

**Comment by LtxProgrammer** [comment]
Do you have any other mods installed? I've had reports saying that the latexes were spawning too frequently, so I think this is a issue with your mod environment.

**Comment by DEE9809** [comment]
i did a test with just the changed mod installed and the same thing happened anyway

**Comment by DEE9809** [comment]
I only did the changed mod on without any mods with it, and it still had the same problem with just a few specific latex beasts spawning

**Comment by LtxProgrammer** [comment]
There's not enough information on this issue to determine what's wrong. The only code that's different between the entities you specified and the ones not spawning is a check for the world's sea level.

Is the world generating normal terrain (Different biomes, varying terrain heights)?

**Comment by LtxProgrammer** [comment]
Stale; reopen if you have more information.
