### ISSUE TITLE
FEATURE: Visit the inventory of a tamed Dark Latex, or give it items, equipment, etc

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1165]
Tamed Dark Latex can travel 和 fight with the player, so is it possible to give the player access to their inventory and give them equipment such as armor, weapons, or tools? Maybe can let them help the player carry things as well.
(adult latex only)

**Comment by LtxProgrammer** [comment]
Moved to #1139
