### ISSUE TITLE
Tweakage FreeCam will cause crash in some forms

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1166]
Dark Dragon will cause crash when Freecam enabled
It seems that this is the case with winged forms.
[crash-2024-11-10_09.10.47-client.txt](https://github.com/user-attachments/files/17689899/crash-2024-11-10_09.10.47-client.txt)
[crash-2024-11-10_09.10.47-server.txt](https://github.com/user-attachments/files/17689900/crash-2024-11-10_09.10.47-server.txt)

**Comment by Y1rd** [comment]
Related to #726

**Comment by LtxProgrammer** [comment]
The crash exception thrown in this log doesn't make sense in the context you describe. I'm guessing the real error is only in the full run log. Can you send a relevant `latest.log` file?

**Comment by XiaoTDM** [comment]
Here it is,
[latest.log](https://github.com/user-attachments/files/17878597/latest.log)

**Comment by XiaoTDM** [comment]
I'll test it this weekend, I'm not very free at other times...

**Comment by XiaoTDM** [comment]
Well, it was fixed.
