### ISSUE TITLE
This MOD does not work on any MOD server side

### ISSUE THREAD

**Issue by hhdsjgit** [LtxProgrammer/Changed-Minecraft-Mod#1168]
Sever PlayerMixin Injection failed
and
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError
![bandicam 2024-11-10 22-09-34-288](https://github.com/user-attachments/assets/691a87dd-2266-4a88-a0c2-9706bf4bfe50)
![bandicam 2024-11-10 22-09-30-339](https://github.com/user-attachments/assets/4d5059d6-d399-4925-8f70-b34d6990b6fa)
![bandicam 2024-11-10 22-09-24-696](https://github.com/user-attachments/assets/d1a626d3-ebad-4bc8-a38a-ffd49682edd4)
![bandicam 2024-11-10 22-09-09-706](https://github.com/user-attachments/assets/8d5c9835-b356-41bd-9daa-e372fd73e316)

**Comment by LtxProgrammer** [comment]
Changed requires forge version 40.2.0 or later

**Comment by hhdsjgit** [comment]
Use FORGE 40.2.18 Unable to start server.

**Comment by LtxProgrammer** [comment]
The errors in the log you sent indicate the environment is missing certain forge classes. Could it be possible your server is misconfigured?

**Comment by hhdsjgit** [comment]
Probably because this file : changed.refmap.json

**Comment by LtxProgrammer** [comment]
I tested 0.14 on a server before release, so it has to be your environment.

`InjectionError: Critical injection failure: Argument modifier method foodEfficiencySwimming(F)F in changed.mixins.json:entity.PlayerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s).`

This error suggests you have a mod installed that edits player code significantly.

**Comment by hhdsjgit** [comment]
How can I fix this issue?

**Comment by hhdsjgit** [comment]
So how can you run this mod normally on the server side?
I don't know how to fix it.

**Comment by Y1rd** [comment]
> How can I fix this issue?

You really need to provide a log.

**Comment by LtxProgrammer** [comment]
This issue should be fixed with the tagged commit, but I have no sure way of testing.

**Comment by LtxProgrammer** [comment]
Closing, assumed fixed
