### ISSUE TITLE
issues with the UniversalAbilitiesEvent

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#1171]
idk why and how but the event is not called when is need making the possibility to add new Universal Abilities be limited by mixins

https://github.com/user-attachments/assets/7c536f65-fc64-4ead-a015-5fded3390901

**Comment by LtxProgrammer** [comment]
Check earlier in your logs, that event is fired when the variants are registered on game launch.

**Comment by Foxyas** [comment]
> Check earlier in your logs, that event is fired when the variants are registered on game launch.

i check it and still any of the loggers was called and i can see that the event is not called due the universal abilities not being add when the condition is applied 

i check if was a issue with the events due my issues with them before *[because i'm dumb]* but all the others events of the API are working just fine

**Comment by Foxyas** [comment]
![image](https://github.com/user-attachments/assets/093d45c5-7724-4044-ab40-890b438c9fc1)
![image](https://github.com/user-attachments/assets/1bfa07a8-c9fa-4ad5-be50-5483350a1248)

**Comment by Foxyas** [comment]
question, the MinecraftForge.EVENT_BUS.post(event); call the event and set the abilities list or just call the event?

**Comment by gengyoubo** [comment]
Can I see the code?

**Comment by gengyoubo** [comment]
Screenshots are fine too.

**Comment by Foxyas** [comment]
> Can I see the code?

The code is just a normal execution of the event like


```java

//Imports here


@Mod.EventBusSubscriber
public static class className {
     @SubscribeEvent
     public static void CoolVoidName(TransfurVariant.UniversalAbilitiesEvent event){
    //A logger to show if the event is called
    // event.addAbility here
   }
}
```

**Comment by Foxyas** [comment]
> Can I see the code?

The video show the code aswell

**Comment by gengyoubo** [comment]
Did you register the custom SubscribeEvent? It doesn't look like it belongs to forge in any way

**Comment by gengyoubo** [comment]
be like:
```
public class CustomEvent extends Event {
    private final String message;

    public CustomEvent(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }
}
```

**Comment by Foxyas** [comment]
> be like:
> ```
> public class CustomEvent extends Event {
>     private final String message;
> 
>     public CustomEvent(String message) {
>         this.message = message;
>     }
> 
>     public String getMessage() {
>         return message;
>     }
> }
> ```

That would create a new event and i'm trying just to execute the event

**Comment by gengyoubo** [comment]
> idk why and how but the event is not called when is need making the possibility to add new Universal Abilities be limited by mixins
> 
>  2024-11-12.00-45-15.mp4

What is this SubscribeEvent about?

**Comment by Foxyas** [comment]
> > idk why and how but the event is not called when is need making the possibility to add new Universal Abilities be limited by mixins
> > 
> >  2024-11-12.00-45-15.mp4
> 
> What is this SubscribeEvent about?

The @SubscribeEvent is a Anotation that "say" that X method will be executed when the Event selected in the method is called

**Comment by gengyoubo** [comment]
That's not what I'm saying, I'm saying what are you doing with the time you're trying to call?

**Comment by Foxyas** [comment]
> That's not what I'm saying, I'm saying what are you doing with the time you're trying to call?

Oh the code just add one new universal Ability if the Entitytype is A latexs and is not a partial Latex

**Comment by gengyoubo** [comment]
Is there no problem with the class being renamed?

**Comment by Foxyas** [comment]
i test using the own Changed Workspace and still the the event is not called 


code is 
![image](https://github.com/user-attachments/assets/0c16e8d2-c00f-44e1-bf37-56d4b8fd1a64)
```
package net.ltxprogrammer.changed.TESTSTUFF;

import net.ltxprogrammer.changed.entity.variant.TransfurVariant;
import net.ltxprogrammer.changed.init.ChangedAbilities;
import net.ltxprogrammer.changed.init.ChangedTags;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber
public class testClass {

    @SubscribeEvent
    public static void lol(TransfurVariant.UniversalAbilitiesEvent event){
        event.addAbility(event.isOfTag(ChangedTags.EntityTypes.LATEX),ChangedAbilities.PUDDLE);
    }
}
```

**Comment by Foxyas** [comment]
maybe i find out why, the builder is registered before the event even be able to call and i find out that because i try use a mixin to add a universal ability in the method "<init>" at "TAIL" and the objects [Builder and the Transfur Variants] was not even registered causing a crash

**Comment by Foxyas** [comment]
i check it more and i saw that for some reason not matter where the event is posted the event will not be post 


i try make the event be posted in the Build method but still is not called

**Comment by Foxyas** [comment]
maybe a option to fix that would be adding a method to add a ability in the player TransfurVariantInstance? 
add the universal abilities when the Instance is created or just create a method to add a Ability instance in the list

**Comment by Foxyas** [comment]
i make it working BUT i move the Event to the TransfurVariantInstance Instead of the Builder Of the TransfurVariant, because for some REASON that i don't understand why yet the event is not called in the Build of the TransfurVariant

**Comment by Foxyas** [comment]
the line that i change
```java
public TransfurVariantInstance(TransfurVariant<T> parent, Player host) {
        this.parent = parent;
        this.entity = parent.generateForm(host, host.level);
        this.host = host;

        this.transfurMode = parent.transfurMode;

        var builder = new ImmutableMap.Builder<AbstractAbility<?>, AbstractAbilityInstance>();
        List<Function<EntityType<?>, ? extends AbstractAbility<?>>> list = new ArrayList<>(parent.abilities);
        var event = new TransfurVariant.UniversalAbilitiesEvent(list);
        MinecraftForge.EVENT_BUS.post(event);
        list.forEach(abilityFunction -> {
            var ability = abilityFunction.apply(this.parent.getEntityType());
            if (ability != null)
                builder.put(ability, ability.makeInstance(IAbstractChangedEntity.forPlayer(host)));
        });
        abilityInstances = builder.build();
        if (abilityInstances.size() > 0)
            selectedAbility = abilityInstances.keySet().asList().get(0);
    }
    ```

**Comment by Foxyas** [comment]
and btw when i try use a mixin to Inject a ability in the `TransfurVariant.Builder` cause a crash saying that the Object don't was Registered

**Comment by Foxyas** [comment]
anyway that fix that i make fix the issue with the event BUT maybe can cause a issue with variants that have a Selected Ability List and would not be the good idea to add a Ability for a Transfur that have a specific Ability list

**Comment by Foxyas** [comment]
maybe a solution would have a boolean to lock the ability list but idk

**Comment by LtxProgrammer** [comment]
I think the event is being broadcasted to early in the mod loading process.

**Comment by Foxyas** [comment]
> I think the event is being broadcasted to early in the mod loading process.

I did some changes and that fixed but instead of Being in the builder of the transfur it's had to be in the Creation of the Transfurs Variant Instance 

Idk if you would like that change but i make a pull request showing what i change in the code

**Comment by Foxyas** [comment]
> I saw that, but I wanted to have the event only happen once at launch.

I don't know if this is possible because I try to use several methods, like having the event be executed before the construction of the Builder of Transfur Variants and making return a list and with that list added to all variants that meet the criteria,add the event handle in the builder [public void i mean], and other kind of method like this but all my attempts fail

you have more experience than me so i guess that you can figure out something =/

**Comment by Foxyas** [comment]
even mixins fail because the object was not registered when the mixin tried to add the code that apply the extra ability

**Comment by LtxProgrammer** [comment]
The `MinecraftForge.EVENT_BUS` is shutdown until the mods have completed loading.

**Comment by Foxyas** [comment]
> The `MinecraftForge.EVENT_BUS` is shutdown until the mods have completed loading.

oh so that explain alot of thing lol

**Comment by LtxProgrammer** [comment]
I swapped it to `FMLJavaModLoadingContext.get().getModEventBus()`, and I believe it will work.

**Comment by Foxyas** [comment]
> I swapped it to `FMLJavaModLoadingContext.get().getModEventBus()`, and I believe it will work.

hoping for good luck :D

**Comment by Foxyas** [comment]
Hey btw could you add a method for add a Ability for a Transfur Variant Instance? :>

**Comment by Foxyas** [comment]
Like a addAbility(), i'm thinking in create a feature where the old you get More Abilities you unlock and a method to add a Ability would help with that alot :>

**Comment by LtxProgrammer** [comment]
I had considered such a feature myself.

**Comment by Foxyas** [comment]
> I had considered such a feature myself.

That would make a little sense, wouldn't it? Like you wouldn't just know how use the specime power instantly after being transfurred

**Comment by LtxProgrammer** [comment]
@Foxyas have you been able to use this event properly since the commit I made? Or are you waiting for the mod version to go live?

**Comment by Foxyas** [comment]
> @Foxyas have you been able to use this event properly since the commit I made? Or are you waiting for the mod version to go live?

I'm planning in Test it tomorrow because i'm busy today

**Comment by Foxyas** [comment]
Hey @LtxProgrammer Could you tell me when normaly you are available to respond?

**Comment by LtxProgrammer** [comment]
> Hey LtxProgrammer Could you tell me when normaly you are available to respond? (What time and in what days)

Got a new job recently, so my hours are different now. But generally after 3p CST on weekdays, and almost all day on weekends.

**Comment by Foxyas** [comment]
> > Hey LtxProgrammer Could you tell me when normaly you are available to respond? (What time and in what days)
> 
> Got a new job recently, so my hours are different now. But generally after 3p CST on weekdays, and almost all day on weekends.

Alright thanks

**Comment by Foxyas** [comment]
i pull the changes in my workspace and create this test file
```java
package net.ltxprogrammer.changed.TESTSTUFF;

import net.ltxprogrammer.changed.entity.variant.TransfurVariant;
import net.ltxprogrammer.changed.init.ChangedAbilities;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber
public class test {

    @SubscribeEvent
    public static void testVoid(TransfurVariant.UniversalAbilitiesEvent event){
        event.addAbility(ChangedAbilities.CREATE_HONEYCOMB);
    }
}

```

**Comment by Foxyas** [comment]
i did the build task and use that mod file to open the game

**Comment by Foxyas** [comment]
and nop is still buggy
![image](https://github.com/user-attachments/assets/22dbba99-2e31-42ba-a826-cb025060e56a)
![image](https://github.com/user-attachments/assets/8cbc05ae-df56-492b-91ef-58dd075b89da)

**Comment by Foxyas** [comment]
¯\_(ツ)_/¯

**Comment by gengyoubo** [comment]
I was wondering if it would be possible to write a development document to help us develop the mod?

**Comment by Foxyas** [comment]
> I was wondering if it would be possible to write a development document to help us develop the mod?

I Could help but i don't know about everything in the Mod Api

**Comment by gengyoubo** [comment]
Should we ask him to make a GitHub wiki?

**Comment by Foxyas** [comment]
> Should we ask him to make a GitHub wiki?

I think that they already has that in mind

**Comment by gengyoubo** [comment]
@LtxProgrammer Should we consider making a wiki on GitHub, and then the original wiki would be

**Comment by LtxProgrammer** [comment]
@Foxyas you need to make sure the event listener is on the right event bus. The universal abilities event is posted on the mod loading bus (`FMLJavaModLoadingContext.get().getModEventBus()`). You can register the listener by:
```java
FMLJavaModLoadingContext.get().getModEventBus().addListener(yourFunction);

OR

Changed.addLoadingEventListener(yourFunction);
```

**Comment by Foxyas** [comment]
@LtxProgrammer How i would use that? I need put inside of the Changed.java file?

**Comment by Foxyas** [comment]
> You add it to your main mod constructor. Ex:
> ![image](https://github.com/user-attachments/assets/9901b10b-6bdc-4fbc-aa91-533c47f27459)
> You can also have this code in a separate function called by your constructor. Ex:
> ```java
> void registerEventListeners() {
>     Changed.addLoadingEventListener(ChangedAddonAbilities::addUniversalAbilities);
> }
> 
> // Mod constructor
> ChangedAddon() {
>     registerEventListeners();
> }
> ```

Ok i gonna test it ou again

**Comment by Foxyas** [comment]
maybe a thing that you could do is create a public void in the `Changed.java` that is empty and used for mixins because the "\<init>" don't work well

**Comment by LtxProgrammer** [comment]
You should be able to move your variant registration to your mod constructor.
![image](https://github.com/user-attachments/assets/f2309280-bde6-4e1b-a5f9-b8aafb81787b)

**Comment by Foxyas** [comment]
> You should be able to move your variant registration to your mod constructor. ![image](https://private-user-images.githubusercontent.com/106349281/388206767-f2309280-bde6-4e1b-a5f9-b8aafb81787b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjUwMDksIm5iZiI6MTczMjEyNDcwOSwicGF0aCI6Ii8xMDYzNDkyODEvMzg4MjA2NzY3LWYyMzA5MjgwLWJkZTYtNGUxYi1hNWY5LWI4YWFmYjgxNzg3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNzQ1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzQ3ZTJiNzY0YTA4ODY1ZGM2YWRiZWRiY2U3ZTRiYWM5ZGM0N2ZlMGEyMzQxOGRkZmVlN2JkOTMzOGUwMDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EH8sLUeZTUwi6u1fz8rHpOUPqbL71oewnBqQ7LgliE8)

the small issue is i can't change the main mod file due use mcreator and i'm not fully ready to work in the project without help of the app =/

**Comment by Foxyas** [comment]
> You should be able to move your variant registration to your mod constructor. ![image](https://private-user-images.githubusercontent.com/106349281/388206767-f2309280-bde6-4e1b-a5f9-b8aafb81787b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjUyMDMsIm5iZiI6MTczMjEyNDkwMywicGF0aCI6Ii8xMDYzNDkyODEvMzg4MjA2NzY3LWYyMzA5MjgwLWJkZTYtNGUxYi1hNWY5LWI4YWFmYjgxNzg3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNzQ4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDdjMGE4ZWYzOTAwODg3M2FkM2MxMjA1YmQyN2FiNTUzZTFiMGZmY2E5M2FlMzljOGQ2ZGYxZWQ4Yzc5NGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JHsMkT_mIIe-mdg_jZk6zzFpsnOvfwYZCqUmQQR_O-I)

now i realize why i can't use the Variants in a static moment like 

`public static List<TransfurVariant> AnVariantsList = List.of(ChangedTransfurVariants.GAS_WOLF.get);`

is probably because the Registry is only registered when the Mod instance is created and because that when using in a static moment the object is still not registered and crash the game

**Comment by Foxyas** [comment]
@LtxProgrammer it don't works when i try use the code in the Addon maybe is because that the variants is already registered but works when i add in the main code

**Comment by Foxyas** [comment]
i try again in other way now and still it's only works when i add the line on the top of the `Changed.java`

**Comment by Foxyas** [comment]
@LtxProgrammer How about creating an empty Void in `Changed.java` [or other file] just for the possibility of a mixin for that method and with that add a way to add a universal ability? that could work no?

**Comment by gengyoubo** [comment]
![image](https://github.com/user-attachments/assets/9075ceec-1c10-4d81-9285-71dace5fd254)
Do you know how to open the mod main file?

**Comment by Foxyas** [comment]
> ![image](https://github.com/user-attachments/assets/9075ceec-1c10-4d81-9285-71dace5fd254)
> Do you know how to open the mod main file?


you will need do the Build Task of the IntiliJ App to keep the changes inside of the main mod file

**Comment by Foxyas** [comment]
I changed the main file and did the build thing and still there no chances

**Comment by gengyoubo** [comment]
```
@Mixin(Minecraft_Science.class)
public class test {
@Inject(method = "<init>", at = @At("TAIL"))
    private void init(CallbackInfo ci) {
    IEventBus bus = FMLJavaModLoadingContext.get().getModEventBus();
    ModEventSubscriber_BlockItem.REGISTRY.register(bus);
}
}
```

**Comment by gengyoubo** [comment]
Just use mixin for the module main file! I have tested it and it works!

**Comment by Foxyas** [comment]
> Just use mixin for the module main file! I have tested it and it works!

Try using the Changed One and try add a universal Abilitie
