### ISSUE TITLE
FerriteCore incompatibility?

### ISSUE THREAD

**Issue by scottycool64** [LtxProgrammer/Changed-Minecraft-Mod#1177]
Whenever I try loading the game with FerriteCore enabled, I get sent to a crash-to-menu with a missing font. The generated crash report suspects this mod and FerriteCore to be the issue, but I DO have a LOT of mods.
[crash-2024-11-12_22.49.34-client.txt](https://github.com/user-attachments/files/17782833/crash-2024-11-12_22.49.34-client.txt)

**Comment by scottycool64** [comment]
[2024-11-12-3.log](https://github.com/user-attachments/files/17782843/2024-11-12-3.log)
and the corresponding log file.

**Comment by Divism1234** [comment]
I also am having a problem with FerriteCore and the Changed mod.
crash report: [crash-2024-11-19_21.59.35-client.txt](https://github.com/user-attachments/files/17824164/crash-2024-11-19_21.59.35-client.txt)
log file: [latest.log](https://github.com/user-attachments/files/17824171/latest.log)

**Comment by gengyoubo** [comment]
![IMG_1839](https://github.com/user-attachments/assets/3d4e3d88-87c7-4168-bc05-cecd2d0d6151)
![IMG_1840](https://github.com/user-attachments/assets/dac3f1e8-de5d-41e5-82c0-4a48bbc99251)

**Comment by Park1423** [comment]
That's weird. I've got two separate modpacks that both have FerriteCore and Changed and both of them work fine.

**Comment by LtxProgrammer** [comment]
Tested as fixed.
