### ISSUE TITLE
Game Crash - Exit Code 1

### ISSUE THREAD

**Issue by SingularProgrammer** [LtxProgrammer/Changed-Minecraft-Mod#1178]
Greetings,
When I try to run the game it crashes and gives an error “exit code: 1” and goes back to the launcher. How do I solve this problem?

[debug.log](https://github.com/user-attachments/files/17791436/debug.log)
[latest.log](https://github.com/user-attachments/files/17791437/latest.log)
![Launcher Log Screenshot](https://github.com/user-attachments/assets/ff02614c-0199-47ad-a527-75cf603fe2be)

**Comment by LtxProgrammer** [comment]
The `java.lang.IllegalargumentException: Block{null} has property: covered_with with invalidly named value: wh[CTRL CHAR]te_latex` suggests the mod file is corrupted.

**Comment by SingularProgrammer** [comment]
I re-downloaded the latest version of the mod from curseforge and verified the size of the jar file, but I still get the same error.

**Comment by SingularProgrammer** [comment]
@LtxProgrammer
I re-downloaded the latest version of the mod from curseforge and verified the size of the jar file, but I still get the same error.

**Comment by SingularProgrammer** [comment]
Problem solved. The problem is due to Java localization. Solution for those who have the same problem: 

- Open forge version profile from Launcher, 
- add `-Duser.country=US -Duser.language=en` code to JVM variables.

Similar problem can happen in other mods. The reason is that languages with special characters (for example Turkish) are a problem. To solve this problem, the JVM localization needs to be changed. Then you can set the desired language as the game language in the game settings.
