### ISSUE TITLE
(Dev Build) dark latex entites appear to take damage in white latex pillars, but no damage is dealt and no hurt sound

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#118]
![2022-12-13_16 54 21](https://user-images.githubusercontent.com/117211742/207478024-1741ba6c-4110-4bba-9bb7-37a847ae7a2b.png)
it seems like white latex pillars damaging dark latex creatures may have been attempted to be added as a feature, but no actual damage is dealt, and no hurt sound plays

**Comment by LtxProgrammer** [comment]
This seems to affect all latexes

**Comment by LtxProgrammer** [comment]
This is from the I-frames commit. It doesn't affect gameplay, but it does show sloppy code.
