### ISSUE TITLE
Request:Open a github wiki

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#1180]
I talked to @Foxyas  about this in #1171 , but I reopened the issue screen anyway. My request is if it is possible to delete the original wiki interface, (or port the wiki code to github) and then open the wiki on github. this way it won't be so much of a hassle to develop the attached mods, and most of the mods use the wiki that comes with github to write their development docs.

**Comment by gengyoubo** [comment]
Then leave the wiki writing to me and @Foxyas . We're going to write about how to use the API and stuff like that. (If possible, consider writing a wiki with modular content, like mcmod for example.)
https://www.mcmod.cn/class/7952.html

**Comment by gengyoubo** [comment]
If I'm not mistaken this must be the link. https://changedmc.miraheze.org/wiki/Main_Page.

**Comment by Y1rd** [comment]
A github wiki could be much nicer, however, it's much harder to contribute on a github wiki as people without write access have to clone the repo, create a wiki on their own repo and copy the original repo's over. Compared to just hitting the edit button.
Although, several parts of the wiki do need a rewrite or information added. So, I'm not sure.

**Comment by gengyoubo** [comment]
I came up with the idea of writing wiki-like functionality with Mk documentation.

**Comment by Y1rd** [comment]
> I came up with the idea of writing wiki-like functionality with Mk documentation.

Maybe a github repo that runs a webpage? And all the information are put into easily editable markdown documents that are automatically translated into html.

It would require setup before hand and possible decision on what to make it look like (using css). But the end result is that anyone can easily edit the md files to update or add information just by forking the repo and submitting a pull request.

**Comment by gengyoubo** [comment]
I need to debug it.

**Comment by Y1rd** [comment]
> I came up with the idea of writing wiki-like functionality with Mk documentation.

I realize you were talking about MKDocs, haven't heard of it before. I'mma look into it.

**Comment by gengyoubo** [comment]
How about creating a specialized wiki library?

**Comment by gengyoubo** [comment]
https://github.com/gengyoubo/Changed-Module-Development-Documentation/wiki

**Comment by gengyoubo** [comment]
I tried writing it and it felt okay. I'll try to add new content in the future, as far as introducing the game content needs to be reconsidered.

**Comment by LtxProgrammer** [comment]
W.I.P

**Comment by gengyoubo** [comment]
What should we do if we need to modify the github wiki?

**Comment by LtxProgrammer** [comment]
> What should we do if we need to modify the github wiki?

You shouldn't need to.
