### ISSUE TITLE
Can't show oranges without turning on the light and shadow?

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#1186]
![屏幕截图 2024-11-24 204328](https://github.com/user-attachments/assets/296daf56-e241-4e56-bb30-de77fda38ca4)

"This module's orange leaves can only show the oranges on the leaves when the light shadow is not on, and the leaf part of the mapping is pure black, while after the light shadow is on (using complementaryshaders 4.7.2) the orange leaf mapping is normal.

It feels like the testers were testing with the lightshades on and didn't take into account the scenario when they didn't have them on."

**Comment by LtxProgrammer** [comment]
Issue with Minecraft's fast graphics.
