### ISSUE TITLE
Incompatible with OptiFine?

### ISSUE THREAD

**Issue by MkXVIIIrev2** [LtxProgrammer/Changed-Minecraft-Mod#1188]
When i try to use the mod and start MC it doesnt start and crashes, i think my PC isnt the problem, but idk why that happens
no problem with another mods, only optifine

i tried with only those 2, but i only can have activated or changed or optifine, not both

14gb Ram
AMD A8 6500B 
Radeon HD8570D

so... idk why that happens, i want to play with shaders (and some optimization tweaks)

**Comment by LtxProgrammer** [comment]
Known issue, Optifine sucks with other mods. I recommend using Rubidium, and Oculus for shaders.

**Comment by Y1rd** [comment]
> Known issue, Optifine sucks with other mods. I recommend using Rubidium, and Oculus for shaders.

Embeddium is more updated then Rubidium. Rubidium hasn't seen updates in a long time.
