### ISSUE TITLE
[0.14.1-Dev] Quadrupedal forms cannot equip saddles

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#1191]
After the introduction of Curios, players that are a quadrupedal form with the capability of wearing a saddle have no method of equipping it. Curios lists that the saddle can be used in the "Lower Body" slot, which the respective Curio slot is nonexistent for the quadrupedal forms. It is also not possible to equip the saddle through the radial menu. The only method of equipping it is by shift-right-clicking.

**Comment by spacedan228** [comment]
last time i tried, wearing a chest didn't work either
