### ISSUE TITLE
[BUG] 'event.setCanceled' for Benign Wolf still effect after untf.

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1202]
Tf into another form can fix.

[If make it able interact with objects in creative mode? (Like DL Pup)]

Maybe only the unlucky ones who accidentally touch the laser with shorts worn will tf into this latex... ~~No one may like it.~~

**Comment by LtxProgrammer** [comment]
What event is being canceled?

**Comment by Foxyas** [comment]
> What event is being canceled?

well idk if that bug is the same to one that i find out but if you get untransfured WHILE being transfured the game unsync and thinks that you are still transfuring that because that the player become unable to interact with any blocks or items
