### ISSUE TITLE
OptiFine causes an error when starting Minecraft

### ISSUE THREAD

**Issue by D-Dogs** [LtxProgrammer/Changed-Minecraft-Mod#1211]
OptiFine causes an error that prevents Minecraft from working. 
installed - Changed: Minecraft Mod, Changed Addon Plus, OptiFine. version 1.18.2. forge version 40.2.9. disabling Changed Addon Plus does nothing.
when you disable Changed everything starts working.
OptiFine was installed from the official website.

![image](https://github.com/user-attachments/assets/3bbf8888-c990-4f51-80f0-1a8f8b90847a)

**Comment by Foxyas** [comment]
Optifine is not compatible with changed mod

**Comment by D-Dogs** [comment]
and nothing can be done about it?

**Comment by Foxyas** [comment]
> and nothing can be done about it?

Yeah you can use Embiddium or Rubidium   with Oculus to Run Shaders

**Comment by D-Dogs** [comment]
Thank you
