### ISSUE TITLE
Resourcepack & Datapack support

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1217]
Maybe we can use resourcepacks to custom textures and models for latex and blocks, and use datapacks to modify the game mechanics in the mod, as the behavior of latex and some of the block functions, even adding new latex, items and blocks.

If they have already been implemented, can you write a documentation to facilitate development?

**Comment by XiaoTDM** [comment]
@LtxProgrammer 
I wanted to know if we could modify the properties of the latex or create new variants via Datapacks (after tfed)
It seems that the documentation only defines the properties of NPC Latex, and does not mention player Latex, [only here](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/wiki/Transfur-Variants).
If using datapacks, we don't need to create a sub mod (Datapacks are easier to make).

**Comment by LtxProgrammer** [comment]
It's not possible yet. While `TransfurVariant`s are almost in a data-oriented state, the latex entities themselves have incredibly complex models that make them only capable of being defined through code.

`TransfurVariant`s require an entity of type `ChangedEntity` that has all of the properties required data and internal properties to replicate a likeness to a player. Thus if you want to add a new variant (with a new entity), you'd need a sub mod anyways.

**Comment by LtxProgrammer** [comment]
> It seems that the documentation only defines the properties of NPC Latex

To directly answer this, the wiki will contain all of the relevant data-processing capabilities of Changed. So if you don't see it there, it cannot be done.

**Comment by XiaoTDM** [comment]
> It's not possible yet. While `TransfurVariant`s are almost in a data-oriented state, the latex entities themselves have incredibly complex models that make them only capable of being defined through code.
> 
> `TransfurVariant`s require an entity of type `ChangedEntity` that has all of the properties required data and internal properties to replicate a likeness to a player. Thus if you want to add a new variant (with a new entity), you'd need a sub mod anyways.

And what about modifying the original variants? Maybe it can be done?

**Comment by LtxProgrammer** [comment]
Not in the current version.

**Comment by XiaoTDM** [comment]
> Not in the current version.

Is it feasible in principle?
(Well, if it's hard to achieve or you're just lazy to do it, then don't need to do it, maybe you've been quite busy lately.)
