### ISSUE TITLE
croc latex's vision is misaligned

### ISSUE THREAD

**Issue by BecoolTJ** [LtxProgrammer/Changed-Minecraft-Mod#122]
the vision is where their forehead is 
![2022-12-14_14 47 35](https://user-images.githubusercontent.com/111460797/207710924-2d69217d-ffb4-4f10-96ee-377f9ebf3d0b.png)

**Comment by BecoolTJ** [comment]
also do the head spikes really need to be part of the hitbox?

**Comment by BecoolTJ** [comment]
(also hitbox should prbably be at least equal or bigger than centaurs width-wise)

**Comment by asweqr** [comment]
i think the centaur has something simular going on with the vision too
