### ISSUE TITLE
Beyond Earth "space-breathing" datapack doesn't work

### ISSUE THREAD

**Issue by spacedan228** [LtxProgrammer/Changed-Minecraft-Mod#1223]
Title.
It seems like the .json for it is missing, and if it is in the datapack, it doesn't seem like the alien tf can "breathe" in space by default.
https://github.com/user-attachments/assets/7670edf7-290e-4314-b862-68482d533ec5
(tested in the 0.14.1 build assembled a couple of days ago)

**Comment by LtxProgrammer** [comment]
Please reopen, and provide a log, if the bug is replicated.

**Comment by spacedan228** [comment]
strange, also v7.0 is a beta with some things possibly not working, does it work in the stable ver?

**Comment by spacedan228** [comment]
[latest.log](https://github.com/user-attachments/files/18094764/latest.log)
the video is too big for github so here's the log
