### ISSUE TITLE
light latex knight tail armor is bugged

### ISSUE THREAD

**Issue by asweqr** [LtxProgrammer/Changed-Minecraft-Mod#127]
![image](https://user-images.githubusercontent.com/89364836/207785338-ac7872cb-454d-4471-9c6a-db055b3d5af3.png)
![image](https://user-images.githubusercontent.com/89364836/207785451-b4b7e1a3-921d-4cd6-82c7-11aa1f87461e.png)

**Comment by LtxProgrammer** [comment]
This has already been fixed for 0.9
