### ISSUE TITLE
(Enhancement) transfurTolerance gamerule being applicable to humanoid entities

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#149]
for an enhancement; humanoid entities take the same amount of transfur damage as the player for what the value of transfurTolerance is set to

**Comment by bijimio** [comment]
i wonder if this would fix #134 in the process

**Comment by LtxProgrammer** [comment]
Added with 730344b5e3f06c92a9fbf8022a12dfe8bb42c640
