### ISSUE TITLE
Suggestion: Allow choosing infect type regardless of gender

### ISSUE THREAD

**Issue by PsychoCatRyu** [LtxProgrammer/Changed-Minecraft-Mod#152]
Imo, assimilation is better and more fun to use. But what if we could choose any transfur type so that we could use female latex and still be able to use the transfur type we prefer?

**Comment by LtxProgrammer** [comment]
Note to self, feature can be added using new radial ability menu. Saving what infect type is chosen will need to be looked at for abilities (maybe instantiate abilities, instead of using a single instance for all player).
