### ISSUE TITLE
patrons dieing from useing unpurefied syinge spawns invisable special latex NPC

### ISSUE THREAD

**Issue by asweqr** [LtxProgrammer/Changed-Minecraft-Mod#163]
![image](https://user-images.githubusercontent.com/89364836/210451551-b2792a26-c04d-405d-a390-ed3b4bc0b356.png)

**Comment by LtxProgrammer** [comment]
Fixed in commit ab716db2dcec2d3f4f8b12b669fb95526bcf3576
