### ISSUE TITLE
Version 0.9 crashes on servers

### ISSUE THREAD

**Issue by PsychoCatRyu** [LtxProgrammer/Changed-Minecraft-Mod#172]
Offline runs fine, but instantly crashes servers.
Crash report [here](https://www.dropbox.com/s/yg45ddn7vl1mnoi/crash-2023-01-11_22.11.49-fml.txt?dl=0)

**Comment by asweqr** [comment]
i can confirm this happens to me aswell

**Comment by DarkShoro** [comment]
Can confirm, stock server and stock mod, crash server.
