### ISSUE TITLE
all copper blocks and deepslate still have corrupted textures when covered by latex

### ISSUE THREAD

**Issue by BecoolTJ** [LtxProgrammer/Changed-Minecraft-Mod#175]

**Comment by BecoolTJ** [comment]
specifically copper

**Comment by BecoolTJ** [comment]
![2023-01-11_16 07 20](https://user-images.githubusercontent.com/111460797/211937656-3d856f0e-c971-4773-ba3b-cef555e67ab6.png)

**Comment by LtxProgrammer** [comment]
Note to everyone facing this issue, it can be mitigated by pressing F3+T. That of course is no excuse for it to break in the first place; but, at least you can choose to fix it on your end in the mean time.
