### ISSUE TITLE
replication and transfur health glitch

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#178]
all female latex players can only replicate, and all latex players that can replicate don't get health from transfurring humanoids

**Comment by LtxProgrammer** [comment]
Attachment: https://cdn.discordapp.com/attachments/1037069864252227654/1062962121962442845/Minecraft_1.18.2___FPS__178___Mem__25_4170_16384MB___Ping__0_2023-01-12_06-11-34.mp4
