### ISSUE TITLE
Suggestion: more configurable settings

### ISSUE THREAD

**Issue by asweqr** [LtxProgrammer/Changed-Minecraft-Mod#184]
theres been a few things in the mod that would be nice to be able to configure im going to list em here along side the one traveler1127 would like aswell

config or gamerule to edit purification speed (from traveler)

config or gamerule to edit light levels that latex mobs spawn at as its been anoying seeing latexs spawn in fairly well lit houses
even traveler is getting anoyed about this in my own server

config or gamerule to disable vision effects

config or gamerule to disable forced player fusions

config or gamerule to disable armor restrictions

**Comment by LtxProgrammer** [comment]
For the first two, I'll just increase the purification speed; and decrease the light level latexes can spawn at. I'll also reduce the VFX slightly. I won't be adding the last one due to technical issues (how are they supposed to wear it?).
As for the forced player fusions, what do you mean by it?

**Comment by asweqr** [comment]
for forced player fusions what i mean is something to be able to disable the AI from trying to fuse with a fuseable player like the Knight
