### ISSUE TITLE
older versions crash instantly 

### ISSUE THREAD

**Issue by BecoolTJ** [LtxProgrammer/Changed-Minecraft-Mod#215]
something to do with special forms, i was on version 4.2

**Comment by BecoolTJ** [comment]
i didnt know curseforge had multiple pages but was still on 4.2

**Comment by BecoolTJ** [comment]
seems like the new system for special forms isnt backwards compatible with any versions of the mod before it was introduced

**Comment by LtxProgrammer** [comment]
I'm not fixing this, consider it deprecated.
