### ISSUE TITLE
make an "organic" toggle in the infuser.

### ISSUE THREAD

**Issue by BecoolTJ** [LtxProgrammer/Changed-Minecraft-Mod#236]
its kinda annoying if you want to be a certain latex and have the ability to tf but cant because they're organic

**Comment by BecoolTJ** [comment]
this can be viewed as an issue to some people and an enhancement to others so it deserves to be here

**Comment by LtxProgrammer** [comment]
The goal of changed is to accurately represent the world of Changed as close as feasibly possible. Confirmed by DragonSnow himself, the current "organic" transfurs possess no ability to absorb or replicate of their own.

If you want to customize what entities are organic in your world/server however, you can create a resource pack with a file at *data/changed/tags/entity_types/organic_latex.json*.
