### ISSUE TITLE
Huge RAM usage when paired with large modpacks

### ISSUE THREAD

**Issue by LtxProgrammer** [LtxProgrammer/Changed-Minecraft-Mod#284]
Appears to have started since v0.10

**Comment by LtxProgrammer** [comment]
Seems to be from terrablender.

https://streamable.com/o3ef3c

**Comment by Hyper9758** [comment]
How many mods was the lag tested with, I didn't notice anything with >100 mods installed on a server

**Comment by Foxyas** [comment]
I did a test with a very heavy modpack 125 mods and without optifine (I used another optimization mod) and no lag
