### ISSUE TITLE
Items get deleted when player gets absorbed (keepCon: false)

### ISSUE THREAD

**Issue by LtxProgrammer** [LtxProgrammer/Changed-Minecraft-Mod#298]

**Comment by Hyper9758** [comment]
From what Foxyas and I seemed to uncover, this seems to be due to the method of killing the player after they get assimilated

**Comment by Hyper9758** [comment]
I was reading through my server's log  while trying to replicate and it never stated that the player had died

**Comment by Hyper9758** [comment]
I can get a dedicated sever to test this, just message me on discord when I am online

**Comment by LtxProgrammer** [comment]
Tested, and resolved.
