### ISSUE TITLE
(my) patreon form wing render glitch

### ISSUE THREAD

**Issue by FailnNoFail** [LtxProgrammer/Changed-Minecraft-Mod#34]
yeah, okay so the latest update was supposed to fix the improper rigging on the wings, and yeah it did, but uh not for my patreon form, wing rigging on that is still bugged like before
ign is FailnNoFail, same as my username here

**Comment by LtxProgrammer** [comment]
https://github.com/LtxProgrammer/patreon-benefits/commit/fd741577ade1700c7217176136e2252028dd55e9
