### ISSUE TITLE
Aquatic latex have difficulties pathfinding to players outside of the water

### ISSUE THREAD

**Issue by BecoolTJ** [LtxProgrammer/Changed-Minecraft-Mod#342]
just noticed when playing that the shark that was chasing me was unable to pathfind to me on a platform on top of the water but as soon as i got in the water it could

**Comment by BecoolTJ** [comment]
one of them did manage to get up on the raft

**Comment by BecoolTJ** [comment]
> one of them did manage to get up on the raft

though it seems to be non-replicatable

**Comment by bijimio** [comment]
ive seen this problem before too

**Comment by BecoolTJ** [comment]
update: they seem to pathfind on the bottom of the ocean when you exit the water instead of swimming to the water block closest to you
