### ISSUE TITLE
entity Unspecified Tick causing a lag fps

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#351]
With the mod
![2023-03-14_15 24 04](https://user-images.githubusercontent.com/119010731/225102286-8296aa41-665b-41a5-8ca0-b7c10ee9dae2.png)
![2023-03-14_15 24 12](https://user-images.githubusercontent.com/119010731/225102305-b0ce92dc-3f82-46bd-9b89-3c6a81df0aac.png)
![2023-03-14_15 24 19](https://user-images.githubusercontent.com/119010731/225102330-caec3c3d-5ef9-450d-b59c-d484b00bd07b.png)
![2023-03-14_15 24 25](https://user-images.githubusercontent.com/119010731/225102341-6ee9712f-3861-456f-a579-0419fcf25bbd.png)

without the mod

![2023-03-14_15 38 21](https://user-images.githubusercontent.com/119010731/225105186-bcd1a806-3f6b-477e-954a-8fd1cc641b3e.png)

![2023-03-14_15 38 37](https://user-images.githubusercontent.com/119010731/225105152-092d57ca-ecbb-4007-9fa5-3b84e70b0bc8.png)

![2023-03-14_15 39 34](https://user-images.githubusercontent.com/119010731/225105286-18bac7de-2bd0-447c-8066-917bccd357da.png)

**Comment by Foxyas** [comment]
maybe the pale is causing this problem?

**Comment by Speeder323** [comment]
To be fair, in the screenshots it looks like you have Render Distance 12 when you have the mod on (unless I'm bad at reading the F3 menu)
Have you tried disabling the natural latex spread gamerule?

**Comment by Foxyas** [comment]
Yes and the problem is the entitys or the tick of entitys

**Comment by Foxyas** [comment]
I use 8 chunks

**Comment by LtxProgrammer** [comment]
I did a spark profile on v0.10.2 with a simulation distance of 32 chunks, and got insignificant readings. Granted I do have a higher end computer.

**Comment by LtxProgrammer** [comment]
As suggested by the gamerule change in in the screenshots:
![image](https://user-images.githubusercontent.com/106349281/226738019-84f534a4-96f9-41f8-a4db-e96f9ff4739c.png)
Minecraft seems to have a less than Ideal way to spawn entities.
