### ISSUE TITLE
Transfur + Totem Of Undying = Infinite Latex Duplication

### ISSUE THREAD

**Issue by tborg16** [LtxProgrammer/Changed-Minecraft-Mod#354]
My Server (Changed Evade) has discovered a new bug that can cause issues and performance issue in the server. maybe singleplayer too.

By using the Totem of Undying, you can survive the Transfur and can create hundreds and hundreds of duplicated latexes. very big issue
that could effect singleplayer but will impact Servers like mine!

you can view the issue on my youtube video

https://user-images.githubusercontent.com/124600335/226110391-a6145890-69f4-4de7-9500-3007df5b8b16.mp4

**Comment by keenan1127** [comment]
side comment: don't use bazooka like that.
use grenade launcher instead, that way it won't damage blocks.
ik it's protected, but it's better to get into the habit.
