### ISSUE TITLE
AI Doesn't make entities swim upwards.

### ISSUE THREAD

**Issue by kohtalee0910** [LtxProgrammer/Changed-Minecraft-Mod#355]
![image](https://user-images.githubusercontent.com/128257026/226135027-7ecabcbe-8245-4fa3-bc29-a5fe5770157a.png)
As you can see in the attached image, the AI doesn't seem to make the latex swim upwards, which leads to this.

**Comment by BecoolTJ** [comment]
this was already covered by a report i made, they seem to not be able to path-find well to players outside of the water

**Comment by bijimio** [comment]
This was already fixed for 0.11.
