### ISSUE TITLE
When server start up load patreon benefits cause server stuck about 30 minutes 

### ISSUE THREAD

**Issue by BaiTian6641** [LtxProgrammer/Changed-Minecraft-Mod#36]
[Partial log.log](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/10061681/Partial.log.log)

In China, we cannot connect to Patreon directly due to GFW(Great Firewall).

**Comment by LtxProgrammer** [comment]
The mod doesn't connect to Patreon, it only connects to Github.
