### ISSUE TITLE
transfur visual progress bar not synced/showing with all players model on singleplayer, lan server and non lan server

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#392]
with all player model i mean by the models out of inventory and the hand model 

### **Single Player test**

https://user-images.githubusercontent.com/119010731/230699590-6aa0a5e5-adf4-4ef6-939a-2da741c07148.mp4

### **No Lan Server test**

https://user-images.githubusercontent.com/119010731/230699593-a6f578c5-a299-4c24-b77b-64ade7bf4ef7.mp4

### **Lan Server test**

https://user-images.githubusercontent.com/119010731/230699594-3e357a30-27a8-4a04-beae-8daf7d67e370.mp4

**Comment by LtxProgrammer** [comment]
I'm gonna be honest, I have zero idea how this can happen. The inventory render, and the 3rd person render are built off of identical code. I can't even replicate this error. @Foxyas, if you're able to send the log (or steps to recreate), I could look into this error more.

**Comment by Foxyas** [comment]
Ok i go try

**Comment by Foxyas** [comment]
@LtxProgrammer 
https://streamable.com/jwx61p
or 

https://user-images.githubusercontent.com/119010731/231877430-84766e30-8d4b-464e-b3dc-eb8b286d8994.mp4

**Comment by Foxyas** [comment]
I don't think there's any way to solve this so I'll close it when I get home ,now I need to leave

**Comment by LtxProgrammer** [comment]
I don't mean the live log, I mean the full .log file

**Comment by Foxyas** [comment]
[latest.log](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/11226322/latest.log)


> I don't mean the live log, I mean the full .log file

**Comment by Foxyas** [comment]
all the 3 tests
with optifine 
without fps mods
with rubidium

**Comment by LtxProgrammer** [comment]
It's probably from optifine, it's also causing errors with hair.

**Comment by Foxyas** [comment]
> It's probably from optifine, it's also causing errors with hair.

the tests performed in the video is 
With rubidum 
First test

Without any fps mod 
second test 

With optifine 
third test

**Comment by Foxyas** [comment]
optifine didn't have any conflicts at least not in the game itself

**Comment by Y1rd** [comment]
Doing a bit of testing, this happens if you have Rubidum (aka Sodium) installed (at least for me).
Most likely a rendering error/conflict due to how heavily Rubidum changes the rendering code.

**Comment by Foxyas** [comment]
I closed the problem because I don't think there is a way to fix this because it is a render change issue of a fps bost mod

**Comment by Y1rd** [comment]
Actually Foxyas, this could be fixed.
