### ISSUE TITLE
Some blocks don't have integration with Presence Footsteps

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#393]
### In order of appearance:
* Vent Wall
* White Latex Block
* Infuser
* Purifier
* Dark Latex Block
* Box Pile
* Vent Hatch
* Retinal Scanner
* Laser Emitter
* Lab Table
* Cardboard Box
* Iron Crate
* Lab Door
* Blue Lab Door
* Computer
* IV Rack
* Speaker
* Vent Fan
* Wolf Gas Canister
* Canned Peaches
* Latex Puddles (if you can walk on it long enough to hear it...)

### Relevant Video:

https://user-images.githubusercontent.com/100542617/230703145-3d44ac4f-fed4-41c7-9da2-0bc9d0c72944.mp4

**Comment by LtxProgrammer** [comment]
After looking into this issue, it appears to be from Presence Footsteps being an over-engineered mod, and requiring mod developers to create their own block -> sound map, instead of determining sounds by block type. However, I will look into creating a block -> sound map for the Changed mod.

**Comment by Y1rd** [comment]
Alright cool, no more (mostly) silent footsteps. Thanks! :D

**Comment by Y1rd** [comment]
Actually, something just came to my mind @LtxProgrammer
Presence Footsteps has a option to change the "stance" from 2 legs to 4 legs. Making the footsteps sound as if you had 4 legs, obviously.

Unsure how easy or if possible, but this option could be perhaps changed by the mod whenever you become the fused knight transfer to 4 legs (because... you have 4 legs.)

**Comment by LtxProgrammer** [comment]
I'll look into that.

**Comment by LtxProgrammer** [comment]
Done. Need to possibly implement custom processor, for slithering.
