### ISSUE TITLE
Server crash issue (WhiteLatex)

### ISSUE THREAD

**Issue by tborg16** [LtxProgrammer/Changed-Minecraft-Mod#400]
I been receiving crash reports upon joining the server regards to the Changed Mod.

Here the Report
File below
[Crash Report (Whitelatex).txt](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/11240485/Crash.Report.Whitelatex.txt)

Upon joining the Server. you will be falling to void (entire server. aka tps has frozen in time)
10 - 20 seconds later. the entire server crashes. Watchdog has proceed to kill the server

Disabling watchdog fixes but there still lag spikes that are caused by the mod.

**Comment by Y1rd** [comment]
Looking at the crash report, the game hangs while executing code for the block WhiteLatex.
Gonna see if I can recreate this on a clean setup (Forge + Changed Mod only).

**Comment by LtxProgrammer** [comment]
Error seems to be from either crayfish's funiture, or some sort of optimization mod. Crash summarized:

Minecraft posts a world tick event -> 
Post office from mrcrayfish's furniture ticks -> 
tries to get a block entity -> 
tries to read chunk from cache (doesn't find it) -> 
a modded function called `getChunkBlocking` calls minecraft's blockable event loop (halts execution until tasks are complete) -> 
Minecraft waits for a non-existant (or unending) tasks ->
hang watchdog sees this world tick take 1 minute (too long) -> 

**CRASH**
