### ISSUE TITLE
elytra bug

### ISSUE THREAD

**Issue by Minecharftgamer** [LtxProgrammer/Changed-Minecraft-Mod#402]
english not gud
so whenever i fly into a cornor with an elytra i cant move and i float and cant do anything and if i use a perl game crash more info at Voltage9000#7885

**Comment by LtxProgrammer** [comment]
If you can send a crash log, that would help greatly.

**Comment by LtxProgrammer** [comment]
Issue is not clear enough to work on, closing for now until clarified.
