### ISSUE TITLE
Infuser Table not working

### ISSUE THREAD

**Issue by PearKing05** [LtxProgrammer/Changed-Minecraft-Mod#410]
**I'd like to preface this with the following: I'm not good at reporting issues, bugs, or other technical problems**

With that out of the way, in version 0.11.1 the infuser table doesn't let you craft anything in it. I've tried new, and old forms, and also tipped arrows to no avail. I've also noticed others having the same problem.

**Comment by LtxProgrammer** [comment]
Already fixed in dev build

**Comment by PearKing05** [comment]
> Already fixed in dev build

What's the wait time on the release?

**Comment by LtxProgrammer** [comment]
Patience.

**Comment by PearKing05** [comment]
> Patience.

I'm not rushing, just curious.
