### ISSUE TITLE
Cant run or swim when transfur 

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#420]
(Minecraft Server Ping Bug)
when transfur the blinding effect is given the player is unable to run because in server count that you still have blindness activated maybe just increasing the time of the blinding effect a little 40-50 ticks (2 or 2.5 seconds) is good

**Comment by Y1rd** [comment]
This might be hard to fix because potions effects overall act wacky with high ping. You might leave a area with a beacon for example, and it takes about 5 seconds before those potions effects actually remove themselves (after the timer hits 0:00).
