### ISSUE TITLE
yufeng & red dragon torso animation error

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#45]
the yufeng, and also the red dragon since it was based off of the yufeng, have an animation error that causes their torso to slightly clip through their legs, both models are fine in blockbench so it is most likely an animation error
![2022-11-24_01 23 30](https://user-images.githubusercontent.com/117211742/203878582-d4af84ee-4723-47a4-8dd3-3a4fabaeb961.png)

**Comment by LtxProgrammer** [comment]
Low priority issue, will fix by v0.9
