### ISSUE TITLE
Laboratories cannot be located using /locate

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#466]
![Screenshot_20230715_205538](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/100542617/b73bc1f6-a5c9-4e94-aa46-90773b099deb)

**Comment by BecoolTJ** [comment]
from what i remember this is an issue with how the structures actually generate and would require a recode of structure generation

**Comment by Y1rd** [comment]
If so, the vanilla system should be easy. You can add structures via datapacks.
Unless, I'm entirely wrong...
