### ISSUE TITLE
in The End and The Nether generate latex animal

### ISSUE THREAD

**Issue by ProgrammerMao** [LtxProgrammer/Changed-Minecraft-Mod#470]
I went latex animals can generate in The End and The Nether
And can use /gameruler to choise true or false.

**Comment by Y1rd** [comment]
What?

**Comment by Y1rd** [comment]
Oh, I see now.

**Comment by ProgrammerMao** [comment]
> What?
Sorry, some of my words were directly translated using translation software, which made it difficult to understand. I have modified some of the words in the original text and now I should be able to understand the meaning of the original text

**Comment by LtxProgrammer** [comment]
Is this a bug? Or is it a feature request? As in, are you saying that latexes are spawning in the nether/end and they shouldn't be, or are you saying that latexes should spawn in the nether/end?

**Comment by ProgrammerMao** [comment]
This is a feature request, not a bug.
I hope that latexes should spawn in the nether/end.
Because I am a video creator, when I explore nether/end, no latexes chasing me, I think this video will lack the fun of mod.
