### ISSUE TITLE
bug in tail model

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#49]
form light latex wolf/female
![2022-11-27_14 31 00](https://user-images.githubusercontent.com/119010731/204150807-f0613668-9465-4ec6-a405-0b8dd769bfbb.png)
![image](https://user-images.githubusercontent.com/119010731/204150828-bd3e1c17-03e9-479c-8030-53ee1aae84bf.png)
form light latex knight
![image](https://user-images.githubusercontent.com/119010731/204150839-1e32118c-d7c3-4e1a-98c1-132328804323.png)
this was the only ones i found maybe there could be more =]

https://user-images.githubusercontent.com/119010731/204151354-78c47a95-dbec-4973-a4bf-5692f8facf8d.mp4

**Comment by Foxyas** [comment]
I forgot to mention but the chests don't have the textures of (covered_with)

**Comment by LtxProgrammer** [comment]
Updated title for already fixed bug

**Comment by Foxyas** [comment]
Oh ok

**Comment by LtxProgrammer** [comment]
Recently tested tail bug, could not replicate.
