### ISSUE TITLE
[Dev] Latex covered blocks' textures are attempting to render from normal block atlas, this time with the whole block texture.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#492]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/309fd38f-91ad-45ee-848a-072f161cebd8)

**Comment by LtxProgrammer** [comment]
Did you have anything configured weird with your mods? What block is it?

**Comment by LtxProgrammer** [comment]
Nevermind, I see it now.

**Comment by LtxProgrammer** [comment]
Issue appears to be from Rubidium, I'll create a mixin.
