### ISSUE TITLE
Latexes wearing elytras can get stuck on blocks, which can cause a crash.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#494]
If a latex player with an elytra crashes into a corner they may become stuck, and the player's legs and arms will disappear, if they try to use a firework to escape the situation, it can cause the game to freeze and crash.
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/0431cb26-5690-4158-8c36-ba432a3c4039)
the crash caused by this has a non zero exit value.

**Comment by LtxProgrammer** [comment]
Can you see if you can find the crash log for this? A non-zero exit value only indicates the program exited with a failure. It would be in `run/logs/`.

**Comment by PalTheTaur** [comment]
So, I was able to reproduce this glitch, no crash log as the crash is caused by the game locking up completely, but the server does spam 
[Server thread/ERROR] [minecraft/Util]: Invalid entity rotation: NaN, discarding.
inside the console

**Comment by LtxProgrammer** [comment]
Error appears to be from a `NaN` delta movement value, unsure if this bug is specific from the changed hitboxes?

**Comment by LtxProgrammer** [comment]
The bug seems to happen when a player with elytra glides down in a corner perfectly negating gravity. Their movement speed is perfectly 0, and `LatexVariantInstance.multiplyMotion()` never assumed such a case could happen.
