### ISSUE TITLE
Config file to add/remove target entities for Latex Creatures

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#503]
Cool little idea, have a config file to remove or add entities that will be targeted by latex creatures (other than the vanilla Zombies and Skeletons).
Could be nice for modpack devs or anyone really to add additional entities to the list, like the zombies from [Born In Chaos](https://www.curseforge.com/minecraft/mc-mods/born-in-chaos), for example. Or just stop the latex creatures from targeting any entities at all (except for the player of course).

**Comment by LtxProgrammer** [comment]
See [tags/entity_types/humanoids.json](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/blob/master/src/main/resources/data/changed/tags/entity_types/humanoids.json)

**Comment by Y1rd** [comment]
Noted, thank you.
