### ISSUE TITLE
Latex blocks incorrectly culling unstable blocks

### ISSUE THREAD

**Issue by ivemadeanaccounttoaskquestions** [LtxProgrammer/Changed-Minecraft-Mod#53]
(dont know how to add labels)
if a door is covered and a block next to it is also covered then for some reason you can see through the block (happens with vanilla doors)
-Dark Latex (1 block):
![Dark latex](https://user-images.githubusercontent.com/73357619/204468687-d42c2418-e88a-4a86-836a-f1787a4bbfb8.png)
-Dark Latex (2 blocks):
![Dark latex 2block](https://user-images.githubusercontent.com/73357619/204468848-c63b661c-6fa9-4b6c-a2a9-16d3217a6fcc.png)
-White Latex (1 block):
![White latex](https://user-images.githubusercontent.com/73357619/204469047-edda7098-2576-4c45-a69e-b4c8256d9c9e.png)
-White Latex (2 blocks):
![White latex 2block](https://user-images.githubusercontent.com/73357619/204469654-e9bdd1fd-249d-4e87-add8-dd6d8a46dfa9.png)
(Only if both doors and blocks are covered):
![Only covered blocks](https://user-images.githubusercontent.com/73357619/204470162-80177171-d9fd-49b7-bf26-cd5d6e49d103.png)
![Only covered blocks2](https://user-images.githubusercontent.com/73357619/204470197-e31fa1f5-8d39-46ef-8c1f-5f452f2ba5da.png)

**Comment by LtxProgrammer** [comment]
`BlockBehaviourMixin.skipRendering()` may be detecting block stability incorrectly
