### ISSUE TITLE
Incompatibility with create mod

### ISSUE THREAD

**Issue by Mass1milian0** [LtxProgrammer/Changed-Minecraft-Mod#535]
unrelated to #528 

this happens on client, when changed is loaded together with create mod it gives error:

`java.lang.IllegalStateException: Uploader not created, a dependency for another mod may be missing.`

versions:
Forge: 40.2.10             
Create: 0.5.1.c             
Flywheel (bundled with create): 0.6.9-101           
Changed: 0.12                

full crash report attached
[crash-2023-09-21_15.08.00-client.txt](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/12685618/crash-2023-09-21_15.08.00-client.txt)

**Comment by LtxProgrammer** [comment]
Already fixed in https://github.com/LtxProgrammer/Changed-Minecraft-Mod/commit/5230e54a1dab83e0320c19b17cb8d85e00a63b45
