### ISSUE TITLE
Bedrock Still having the missing texture error  

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#540]
the bedrock texture still having the Missing Texture error
![2023-09-22_13 40 15](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/119010731/6f39f71e-765b-425a-b145-44ef4373dfcb)

**Comment by LtxProgrammer** [comment]
Details on this error are unclear, attempting to reproduce this error myself has led to failure.
