### ISSUE TITLE
Add compatibility with hardcore revival. 

### ISSUE THREAD

**Issue by LavaDogX** [LtxProgrammer/Changed-Minecraft-Mod#546]
When using with the Hardcore Revival Mod, if a player is "Transfured and loses consciousness a endless stream of latex creatures of the type that transfured the player will keep spawning while the player is down but not dead. It will stop when the player "Gives up" or is revived

**Comment by LtxProgrammer** [comment]
What would be the expected behavior here? The latex entity just leaving you, almost dead on the ground? The latex's goal was to transfur you, not kill you.

Presumably the solution to this would be just to skip the revival part and boot the player into the afterlife.
