### ISSUE TITLE
Lootable Syringes should be able to be used globally

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#551]
_Based on a suggestion from the discord in which I cannot remember who created it._
Basically, any syringes found in the chests of structures should be able to be used by anyone as long as it's purified. Unless KeepConscious is on, attempting to use the syringe in a IV rack and sleeping will kick you out of the bed after a few seconds without doing anything.

**Comment by LtxProgrammer** [comment]
Implemented
