### ISSUE TITLE
Latex Players Are Able to Equip Any Item As Armor In Any Slot.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#568]
![Screenshot 2023-10-25 072418](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/c653a209-7281-44ed-bb9d-d81445407d32)
Can be done in survival, without using the /item replace command.

**Comment by Y1rd** [comment]
Honestly, this is kinda funny.
It's not a bug, it's a feature :D
