### ISSUE TITLE
Changed Mod Models in API enhancement 

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#574]
_when is tryed use a model that is "pre made" from changed main mod in this case LightLatexWolfMaleModel this erro happen_ 
```Type 'net.ltxprogrammer.changed.client.renderer.model.LightLatexWolfMaleModel' does not have type parameters```
_and i see in the code the model don't allow to be used for other latex entity only for LightLatexWolfMale and is the same thing for all models,and is because this models are linked to a certain latex entity or entity
It would be nice to have an addition that allow use the Latex Entity models so they can be used by any latex entity renderer;_
like a new class or function like a LatexEntityModel<Latex Entity>
Or just replace the line for T Extends LatexEntity instead of a entity

_If this is impossible due to the way the models are saved or is just very complex to do that, I understand_

**Comment by LtxProgrammer** [comment]
If the need arises for you to use the model, make your entity extend `LightLatexWolfMale` (or whichever entity you're deriving from), but this NEEDS to be solved by adding your own models.
