### ISSUE TITLE
Custom Render For multi Eyes Colors for latexs and transfur players

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#575]
A render that add a sub texture in eyes location for almost all latexs entitys like the visual transfur progress render feature 

The render can use a pre made texture (can be edit by a texture pack) with no color (white) and will be set the color randomly via NBT (using Code HEX the "#colorcode") or a math in an external code the colors can be set using the Color3 

Not all latexs because Isn't all transfurs that can have the eye color change like dark latex wolfs,pups,knight,the horse knight one(i don't remember the name)

optional (a boolean config) that uses the eyes of the player's skin to set the eye color
When on need config to set the eyes location of the player skin OR can be made a pre types like 
Type 1 = Steve eyes type
Type 2 = 2 Pixels Steve eyes type
Etc

**Comment by spacedan228** [comment]
In bad endings of Changed, Colin TF'd into a dl wolf (+pup TF) has his blue eyes, they have white eyes prob cause they have consciousness of the latex.
(+he has his blue eyes in the knight fusion TF)

**Comment by LtxProgrammer** [comment]
I added some basic customize info for hair, iris, and sclera color. All this work is done on the [animation-rework](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/tree/animation-rework) branch.
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/blob/animation-rework/src/main/java/net/ltxprogrammer/changed/entity/BasicPlayerInfo.java
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/106349281/dcdd2a6c-c9f1-4166-ab39-432b8203e2f5)

**Comment by LtxProgrammer** [comment]
Feature complete in [animation-rework](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/tree/animation-rework) branch.

**Comment by spacedan228** [comment]
tbh dark latexes should have that feature work for them too - they're not an exception to the rule/logic (no tfs are)
