### ISSUE TITLE
Compatibility with the Tough As Nails mod

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#576]
Compatibility with a ambient temperature mod would be really cool, wouldn't it? In fact, a leopard doesn't feel that cold because it comes from cold biomes

**Comment by LtxProgrammer** [comment]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/106349281/93f68f5b-86e3-47b0-9489-4be5a14ec555)
Reading the source for tough as nails, freezing is based on `player.getTicksRequiredToFreeze()`, which is currently changed based on the variant the player currently is. No action required.
