### ISSUE TITLE
Null check for .scares() Function

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#578]
Add a Null Check 
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/blob/b109bafde63f30f772ef4bb820806ff05922a4f3/src/main/java/net/ltxprogrammer/changed/entity/variant/LatexVariantInstance.java#L425

check if is null just don't scare any entity

how i found this? I was exploring the code and ended up discovering this "loophole" that doesn't necessarily crash the game but leaves a spam of warnings and BTW you can add a "Variable" call "ANY" for don't scary any entity without necessarily being organic

**Comment by LtxProgrammer** [comment]
use .scares(List.of()) in your variant builder
