### ISSUE TITLE
breath meter increases forever for latexes with extended breath wearing respiration helmets

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#582]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/5c8e34a4-cf26-4e8d-bcf7-e45449cbe523)

breatheMode.STRONG latex forms' oxygen meters will steadily increase indefinitely underwater to the point where it can eventually go off the screen, if the player is wearing a respiration helmet; instead of further slowing oxygen consumption.

**Comment by LtxProgrammer** [comment]
Fixed in fa2ff6b061d527786bd84364b38bed87ea161b3e
