### ISSUE TITLE
Reporting a question

### ISSUE THREAD

**Issue by XIONGCHUMMO** [LtxProgrammer/Changed-Minecraft-Mod#583]
As the photo,while equipping chestplate on muscular latex creatures,clipping happens.
![屏幕截图 2023-11-26 233046](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/44457978/1a90e70e-6e00-4a49-bf0f-7cee6f9a22dc)
![屏幕截图 2023-11-26 232918](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/44457978/3e5ea261-7abc-4d7b-aea7-ba23a7ad8f22)
Would you like to design  new  chestplate models to make them suitable?

**Comment by XIONGCHUMMO** [comment]
Also,the parts to hand things are wrong.It looks like inserting things in arms,not holding things in hands.

**Comment by LtxProgrammer** [comment]
Models are being reworked
