### ISSUE TITLE
Player latexes will spazz out and try to stand up whilst crawling.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#584]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/45e25f9a-8ebf-4af7-9b78-e0d234a56a21

this bug can also interfere with crawling/proning mods.
Interestingly upon further testing, I found this wasn't an issue before v0.12b, since I remember crawling worked as normal In earlier versions.

**Comment by LtxProgrammer** [comment]
Issue only seems to happen when the player is rendered in any way (third person, inventory)

**Comment by LtxProgrammer** [comment]
After reverting faa60fefd839d645f7e3a86252637f988baaa9e6 for testing, the issue originates from the `getDimensions()` mixin
```java
    @Inject(method = "getDimensions", at = @At("HEAD"), cancellable = true)
    public void getDimensions(Pose pose, CallbackInfoReturnable<EntityDimensions> callback) {
        if (ProcessTransfur.ifPlayerLatex(EntityUtil.playerOrNull(this), variant -> {
            callback.setReturnValue(variant.getLatexEntity().getDimensions(pose));
        }));
    }
```
