### ISSUE TITLE
IMPORTANT: Some entities are patron OC's from Changed

### ISSUE THREAD

**Issue by LtxProgrammer** [LtxProgrammer/Changed-Minecraft-Mod#61]
- Dark Latex Yufeng **[Permission confirmed by BaiTian6641]**
- Latex Beifeng **[Permission confirmed by Valurio9683]**
- Latex Blue Dragon **[Permission confirmed by Valurio9683]**
- Latex Hypno Cat **[Permission confirmed by BaiTian6641]**
- Latex Pink Wyvern **[Permission confirmed by Valurio9683]**
- Latex Red Dragon
- Latex Silver Fox
- Latex Watermelon Cat
- Latex Yuin **[Permission confirmed by Valurio9683]**

**Comment by keenan1127** [comment]
the leaf lizard is also not owned by DS

**Comment by BaiTian6641** [comment]
Dark Latex Yufeng now is OK
I contact with owner

**Comment by LtxProgrammer** [comment]
Nice

**Comment by Valurio9683** [comment]
> Nice

You can remove the red panda, it's not OC

**Comment by LtxProgrammer** [comment]
Issue is stale, we've had no issues with unconfirmed variants.
