### ISSUE TITLE
when to use in revive it should not be duplicated

### ISSUE THREAD

**Issue by jfergomez** [LtxProgrammer/Changed-Minecraft-Mod#625]
Hello, I wanted to ask, it should not be duplicated when used in an immortality totem, including the use of normal revives, which causes it to be duplicated infinitely when using revives.

**Comment by spacedan228** [comment]
wasn't that fixed long time ago?
paste a video here so we can know the bug still persists

**Comment by jfergomez** [comment]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/154007506/735f6fc8-a6de-4671-a6d1-5d60584b13b4

this is the reason what is failing

**Comment by jfergomez** [comment]
In another it also happens but in a different version
https://www.curseforge.com/minecraft/mc-mods/playerrevive

**Comment by jfergomez** [comment]
This is what I used to use from another
https://www.curseforge.com/minecraft/mc-mods/revive-me
And that all

**Comment by LtxProgrammer** [comment]
This issue is related to compatibility with revival mods. Seeing as this was already fixed for [Hardcore Revival](https://www.curseforge.com/minecraft/mc-mods/hardcore-revival), I'll mark these other mods as incompatible. No plans exist currently to fix this issue.

**Comment by jfergomez** [comment]
Ok thx
