### ISSUE TITLE
Bedrock textures do not load with the mod

### ISSUE THREAD

**Issue by spacedan228** [LtxProgrammer/Changed-Minecraft-Mod#632]
title.
vanilla Minecraft
![2023-12-21_23 12 30](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/a3f3e2e2-a4c0-4872-bd19-603c65ae74f6)
Minecraft with the Changed Mod
![2023-12-21_23 10 51](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/10ff62f0-bc6e-49f6-baca-9326bed8dd4c)

**Comment by spacedan228** [comment]
a lot of people seem to have this issue, but i don't think it can be fixed

**Comment by Y1rd** [comment]
What is your mod list? Does this happen with just the mod?
@spacedan228

**Comment by spacedan228** [comment]
it had happened with other people, something to do with loading textures, as sometimes reloading textures helps, at least i heard so

**Comment by spacedan228** [comment]
origin of the issue is quite mysterious
