### ISSUE TITLE
[Dev-build] Lab books cannot be used to place more books on a book stack

### ISSUE THREAD

**Issue by spacedan228** [LtxProgrammer/Changed-Minecraft-Mod#639]
Video:
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/4a9c1c87-1ba8-41e6-97f5-4e878d1952f6

**Comment by LtxProgrammer** [comment]
After testing this issue, I was not able to recreate it. Everything works as intended already.

**Comment by LtxProgrammer** [comment]
I will close this issue as stale if nothing comes of this.

**Comment by spacedan228** [comment]
i'll try testing again, might've been fixed by bijimio

**Comment by spacedan228** [comment]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/0c5b0fc0-354f-45f7-abeb-8e039e9d433e)
also that textureless block is the "book stack", for some reason no lab book in creative menu

**Comment by spacedan228** [comment]
but using a book stack item instead works, which is weird.
if this might help, i use forge 40.2.7 (maybe i should try updating)

**Comment by LtxProgrammer** [comment]
What branch is this on?

**Comment by LtxProgrammer** [comment]
Nvm, was able to replicate this issue.
