### ISSUE TITLE
Small "When Transfur" Animation

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#640]
You can made the player play e short animation for when he get tranfured you can use the transfur event and play the animation for the player and when the animation is playing the player cannot move (or just get very slown) and slow to break blocks and cannot place block

And can be a boolean server config to allow or not the transfur animation

The animation can be a very short animation the player go it will rest its hand on its head (if it is transfured with keepConscious true,command or totem) and if it is by IV Rank it may be a small, smooth change from the player model to the transfur model and if it is by an entity or "block transfur" source, the animation can be the player looking at his arms or resting his hand on his head as well

**Comment by LtxProgrammer** [comment]
Replaced with #755
