### ISSUE TITLE
Not Enough Animations won't apply custom animations to players as latex

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#679]
No direct incompatibilities, but it is probably how animations are handled for Changed:MC. The [mod](https://modrinth.com/mod/not-enough-animations) is client side.

**Comment by Y1rd** [comment]
I don't think the crawling animation should apply to legless aquatics.

**Comment by Y1rd** [comment]
I should note, nearly most custom animations don't work. Even item rendering (like backpack mods).

**Comment by LtxProgrammer** [comment]
> I should note, nearly most custom animations don't work. Even custom entity rendering (like backpack mods, or artifacts).

Doesn't surprise me. Latex entities don't inherit the mixin-ed layers that other mods add, nor do they inherit the player's animations.
