### ISSUE TITLE
FEATURE: Grab mechanic

### ISSUE THREAD

**Issue by LtxProgrammer** [LtxProgrammer/Changed-Minecraft-Mod#708]
Latex players could be capable of grabbing players/entities.
This would involve either holding the player in their arms, or to suit the player.

**Entity in the latex's arms**
- [X] Latex can progress the entity's transfur progress -> replication
- [x] Grabbed entity can struggle to escape
- [X] Latex can let go of the entity
- [X] NPC latexes can still target grabbed entity
- [X] Latex can transition into suit mode

**Entity is wearing latex as a suit**
- [x] Latex can progress the entity's transfur progress -> absorption/replication
- [x] Suited entity can struggle to escape (more difficult)
- [X] Latex can let go of the entity
- [x] NPC latexes do not target grabbed entity
- [X] Latex can relinquish control to the grabbed entity, where:
  * Grabbed entity can leave on command
  * Grabbed entity can walk and interact as the latex

**Comment by bijimio** [comment]
2 current issues with the grabbing machanic:
1: there is no cooldown for grabbing, so it is very hard to set a mob down without accidentally grabbing it again.
2: sweeping attacks the player makes can damage entities inside of suit.

**Comment by LtxProgrammer** [comment]
Ref #865

**Comment by LtxProgrammer** [comment]
Commits added that improves this feature
2239d70eaf9c0d70892318ab813efb9c00d2c407
d3062fadcd729da61be2388b47b597e76a7d3cc8

**Comment by hsjdhudn** [comment]
emm, ltx，there is still a problem (do not know if the shadow does not affect the process), in suit mode, after the skull shooter is devoured, He can shoot arrows; although the zombie roar is gone, the archer can shoot arrows

**Comment by LtxProgrammer** [comment]
Tasks are done technically, however I want to improve the graphics before marking this feature complete.

**Comment by gengyoubo** [comment]
Good!That's good idea!
