### ISSUE TITLE
Loading freeze & CTD because of Latex Cover Generation.

### ISSUE THREAD

**Issue by Puridor** [LtxProgrammer/Changed-Minecraft-Mod#723]
First crash:

[crash-2024-01-20_21.46.25-client.txt](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/13999430/crash-2024-01-20_21.46.25-client.txt)

Alt+F4 (latest) log:
[latest.log](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/13999432/latest.log)

**Comment by LtxProgrammer** [comment]
Set `fastAndCheapLatexBlocks` to `true`, and `generateUniqueTexturesForAllBlocks` to `false` in your client config

**Comment by Puridor** [comment]
Please don't close this before I'm finished.
I tried this, and it did not work.

Crash log: 
[crash-2024-01-21_20.41.43-client.txt](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/14002759/crash-2024-01-21_20.41.43-client.txt)

**Comment by Y1rd** [comment]
@LtxProgrammer
