### ISSUE TITLE
Freecam crashes the game as a winged latex when activated

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#726]
Anything that can fly, either creative-like flight or elytra-like.

**Comment by LtxProgrammer** [comment]
Is this a mod?

**Comment by Y1rd** [comment]
> Is this a mod?

[I probably should've linked it.
](https://www.curseforge.com/minecraft/mc-mods/free-cam)

**Comment by LtxProgrammer** [comment]
Do you have a crash log?

**Comment by Y1rd** [comment]
I should really get some more sleep.
https://hastebin.skyra.pw/pinicofena.nestedtext
