### ISSUE TITLE
Not working with a large modpack

### ISSUE THREAD

**Issue by ToxeNRald351** [LtxProgrammer/Changed-Minecraft-Mod#738]
I know it's a pain to manage compatibility with other mods, but I really wish this mod is able to work with other mods. Here're a log and a crash report files
https://drive.google.com/drive/folders/1jndZ8XC2x5vAJ0ttySgy825eV0FVAKhi?usp=sharing

**Comment by LtxProgrammer** [comment]
Set `generateUniqueTexturesForAllBlocks` to `false`, and `fastAndCheapLatexBlocks` to `true` in your client config.
