### ISSUE TITLE
bows crossbows and fishing rod item textures do not animate when in use as any latex form

### ISSUE THREAD

**Issue by asweqr** [LtxProgrammer/Changed-Minecraft-Mod#76]
![image](https://user-images.githubusercontent.com/89364836/205812488-e495edb4-0997-48b8-b705-23669439eeef.png)
vanilla comparasion1
![image](https://user-images.githubusercontent.com/89364836/205812540-0038c438-c68b-4903-af8a-b228c8b87744.png)
almost fully charged up crossbow in latex form (note the latexes arms also do not animate with the crossbow)
![image](https://user-images.githubusercontent.com/89364836/205812771-601dc028-da8a-4f21-82eb-252e5aba8e50.png)
vanilla comparasion almost fully charged crossbow
![image](https://user-images.githubusercontent.com/89364836/205813001-e0e234c0-2256-45fe-a516-4d8d4ea113eb.png)
fully charged bow in latex form
![image](https://user-images.githubusercontent.com/89364836/205813183-eea800db-65c0-48b6-aaf4-13e111534e61.png)
fully charged bow in vanilla player
![image](https://user-images.githubusercontent.com/89364836/205813307-054c194c-2325-4b33-bb46-5e52b708ac34.png)

**Comment by keenan1127** [comment]
also, spyglass and sheild

**Comment by asweqr** [comment]
> also, spyglass and sheild

i already reported the shield in another issue and someone else has already reported the spyglass issue
