### ISSUE TITLE
Something I've had issues with.

### ISSUE THREAD

**Issue by Scout-Gaming-277** [LtxProgrammer/Changed-Minecraft-Mod#762]
So on curseforge there is an issue I'm having with the latest release of the mod. I've tested many different things and noticed it is specifically an issue with the mod version Released on 1/18/2024. I use 1.18.2, What happened is as soon as the game finished loading up, it crashed. It said theres an error ar this bit of code: "java.util.function.Consumer net.ltxprogrammer.changed.client.renderer.animate.AnimatorPresets.wolfLike(net.minecraft.client.model.geom.ModelPart, net.minecraft.client.model.geom.ModelPart, net.minecraft.client.model.geom.ModelPart, net.minecraft.client.model.geom.ModelPart, net.minecraft.client.model.geom.ModelPart, java.util.List, net.minecraft.client.model.geom.ModelPart, net.minecraft.client.model.geom.ModelPart)"

Pls let me know if this is an issue you guys are already trying to fix, if so I may just delete the comment to avoid people thinking it's still a new issue.

**Comment by LtxProgrammer** [comment]
Please either remove the changed addon mod, or downgrade to 0.12.1

**Comment by Scout-Gaming-277** [comment]
I downgraded, mod is working A okay rn. I tried just the Changed:MC mod on its own, which showed its specifically that mod. And since using previous versions is working great, I know it has to just be an issue in the newest release.

**Comment by Scout-Gaming-277** [comment]
I'm using the version released 10/23/2023 now. It's working very well.

**Comment by LtxProgrammer** [comment]
It's broken because the addon mod isn't updated, do consider not using the addon mod, as it will always crash new releases of changed:mc.

**Comment by Scout-Gaming-277** [comment]
ah, that makes sense. I like the addon so I'll stick to older versions of the mod.

**Comment by LtxProgrammer** [comment]
I'm not responsible for compatibility with the addon mod.

**Comment by Scout-Gaming-277** [comment]
Understandable. I will just use what works until the person who made the addon updates it. That or I may end up making different profiles and stuff.
