### ISSUE TITLE
Can't hold Backspace in Sticky Note or Computer Disc

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#768]
In both text editing areas, you cannot hold backspace to keep getting rid of text unlike vanilla textboxes.
~~Side note, I don't think either of them can have special text, like in books (crossout, colored, etc).~~

**Comment by LtxProgrammer** [comment]
Seems like minecraft doesn't send repeat keys to the GUI, but if it's possible with books..
