### ISSUE TITLE
REFACTOR: Rename many things in the mod

### ISSUE THREAD

**Issue by LtxProgrammer** [LtxProgrammer/Changed-Minecraft-Mod#772]
The current naming convention doesn't match what the entities and features represent.
I've spoken with CLKiscool about these, so I'm documenting what will be updated.
- ~~Latex -> Goo (or gooey)~~
- Organic -> Solid (or nothing)
- ~~Dark -> Black~~
- Light -> White
- White -> Pure White
- LatexVariant -> TransfurVariant
- isOrganic() -> isNonGoo()

I'll create a branch for this refactor, and will merge when the IDs are ready to be changed. Because of the updated IDs, saves will break if a fixer can't be made.

Entities will be renamed with "[Gender] [Color] [Latex] [Species] Beast", and IDs will follow `[color]_[latex]_[species]_[gender]`. Note: "Red Panda" would be the species, not the color.

**Comment by Y1rd** [comment]
Should've renamed Organic to "doesn't transfur unless you hit your enemy with a crystal in your hand" smh

**Comment by LtxProgrammer** [comment]
After failing to create my own DFU to update IDs, I've determined I need to look into editing `CompoundTag` to replace outdated entries when they get read.

**Comment by spacedan228** [comment]
goo/gooey doesn't sound as good imo, same for solid

**Comment by spacedan228** [comment]
renaming dark to black and light to white wouldn't make too much sense lore-wise, dark latex was called black only in the soundtrack

**Comment by LtxProgrammer** [comment]
> goo/gooey doesn't sound as good imo, same for solid, especially in the translation.. (pls spare)

"Latex" was a mistranslation of 胶 (jiāo). While "latex" is generally accepted by the community as the term for the goo creatures, it can also have a different connotation to what was indented.

As for "solid" most entries won't have solid in their name, but only be described as such (or non-goo).

**Comment by Y1rd** [comment]
> "Latex" was a mistranslation of 胶 (jiāo). While "latex" is generally accepted by the community as the term for the goo creatures, it can also have a different connotation to what was indented.

Latex isn't a total mistranslation, but it was the closest thing that matched that word (at least at the time).

**Comment by spacedan228** [comment]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/e01ef457-6595-467b-b9e7-73d5a2b33587)
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/8f4d6306-9041-4393-971e-12ae8bfa4d82)
if it wasn't changed to goo in Changed, why it should be changed in this mod that is supposed to be accurate to Changed?

**Comment by spacedan228** [comment]
i will not change "latex" to "goo", because it wouldn't sound right in Russian, as well as just gross.

**Comment by szpigozzzzz** [comment]
well,this just sucks,and it would not pass in in Polish translation because i used Latex as a own word,and changing that would sound gross

**Comment by LtxProgrammer** [comment]
I wasn't a fan of "latex", because it is typically associated with kink-wear. I figured "goo" just better describes the entities with connotation, and because I believe that's what DS originally intended.

**Comment by spacedan228** [comment]
> I wasn't a fan of "latex", because it is typically associated with kink-wear. I figured "goo" just better describes the entities with connotation, and because I believe that's what DS originally intended.

idk, irl raw latex looks pretty similar to Changed latex

**Comment by spacedan228** [comment]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/6b6146a4-1995-4d87-8e3e-00089813fc1b)

**Comment by Y1rd** [comment]
Based on what other people are saying, it may be harder then expected to change the weird to "Goo" since it isn't quite the same in other languages.

**Comment by spacedan228** [comment]
> > I wasn't a fan of "latex", because it is typically associated with kink-wear. I figured "goo" just better describes the entities with connotation, and because I believe that's what DS originally intended.
> 
> idk, irl raw latex looks pretty similar to Changed latex (white, slimy substance)

also idk why do you associate it with "kink-wear", latex rubber is used for quite a lot of things

**Comment by LtxProgrammer** [comment]
Considering the controversial nature of the "latex" -> "goo" change, I will be removing it from this change list. I had taken the time myself to play the recent version of Changed: Special Edition, and noted that Dr. K refers to the gooey beings as "Latex Beast," while also frequently attributing them as "gooey." "Goo" may be a better descriptor than "latex," but it's too baked into world of Changed and it's community to be worth changing.

**Comment by szpigozzzzz** [comment]
good choice man,very good choice

**Comment by gengyoubo** [comment]
![屏幕截图 2024-06-24 173146](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/113955003/23b6082f-b666-4a9d-aa98-b49e8634d37f)
I'm debating between yufeng and beifeng.
Does beifeng need to be translated as “北风” instead of “悲风”?
Does yufeng need to be translated as "驭风" instead of "御风"?

**Comment by spacedan228** [comment]
> I'm debating between yufeng and beifeng. Does beifeng need to be translated as “北风” instead of “悲风”? Does yufeng need to be translated as "驭风" instead of "御风"?

just use the official translation

**Comment by jonjonjongamer** [comment]
i always just associated latex with the weird cheap plaster brand people used to use where i live :p
