### ISSUE TITLE
Legless Transfurs are slower on Ice then a normal/non-legless Transfur

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#780]
They should be faster anyways, it's slippery!

**Comment by LtxProgrammer** [comment]
I'm not sure how this would make sense.

**Comment by LtxProgrammer** [comment]
> > I'm not sure how this would make sense.
> 
> Well you don't have to make them any faster, but they still move slower on ice then normal blocks for some reason.

Oh, that's somewhat intentional. It's because ice has less friction.

**Comment by Y1rd** [comment]
It's a little unbearable unless you sprint jump :P

**Comment by LtxProgrammer** [comment]
Friction and swim speed have been tweaked in 70bfd87fe6e3181021933222c5c5a64d795afe06
