### ISSUE TITLE
Armor Trims (backport mod) don't render on transfurs

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#782]
Using the mod [Armor Trims Backport](https://modrinth.com/mod/armor-trims), if the player is transfur, trims won't be rendered.
At least this happens in 0.13. Unsure if the latest commits fixes this.

**Comment by LtxProgrammer** [comment]
This functionality will be resolved when the mod gets ported to other versions of Minecraft.

**Comment by Y1rd** [comment]
> This functionality will be resolved when the mod gets ported to other versions of Minecraft.

:(
