### ISSUE TITLE
Multiple bugs regarding 0.14 features

### ISSUE THREAD

**Issue by alexbomb6666** [LtxProgrammer/Changed-Minecraft-Mod#790]
## First group:
1. Zombies die of the sun while they are inside you
2. Skeletons somewhat shoot you while being inside yourself.
3. While villager is inside you, it can open doors when you near them (my guess is the navigational AI being still active)
Probable cause: AI of mobs is still active when being in the suit mode, which causes them to still act up. (zombies can also hit you while they control you)
## Second group:
1. Giving control to mobs makes your camera movement wonky. It just shakes violently while violently threatening to make people fall into epilepsy.
2. While mobs control you, your head doesn't look where mob is looking at, so you just keep watching the birds in the sky most of the time (can be seen in third person)
Probable cause: self-explanatory
## Third group:
1. Latex mobs can and will still target a mob that is inside you (but when they see them first).
2. Mobs inside you can also somewhat take damage from you when you sweep with your sword. I might also mention that sometimes a mob also takes damage when you do (i can realistically explain that because of the player not being the armor in the first place
Probable cause: a mob just gets invisible and just tps to player's position all the time. Can be fixed by "hiding" a mob somewhere or just storing it so it won't do anything while in suit mode.
## Fourth group:
1. When you let a mob take control and it goes somewhere far, you teleport back in an instant after you take control afterwards
Probable cause: no idea

**Comment by hsjdhudn** [comment]
what？Is there so many bugs in the 0.14 red P development version? ! I haven't played it, because I have no money and I can't visit Red P.

**Comment by spacedan228** [comment]
wdym, u don't need to be a patron in patreon to get the dev version

**Comment by spacedan228** [comment]
also its hard to let go of grabbed entities

**Comment by hsjdhudn** [comment]
dan288，Emm, what do you mean.........

**Comment by hsjdhudn** [comment]
emm,You mean, you can get the development version without being a sponsor, but how? 
As for the entity that is difficult to give up grabbing, what does it mean? [Doubt]


> wdym, u don't need to be a patron in patreon to get the dev version



> also its hard to let go of grabbed entities (especially if you're trying to do that after entering and exiting suit mode)

**Comment by spacedan228** [comment]
> emm,You mean, you can get the development version without being a sponsor, but how? As for the entity that is difficult to give up grabbing, what does it mean? [Doubt]
> 
> > wdym, u don't need to be a patron in patreon to get the dev version
> 
> > also its hard to let go of grabbed entities (especially if you're trying to do that after entering and exiting suit mode)

use gradlew.bat (download source code, open cmd prompt, go to the source code folder, enter "gradlew.bat build"

0.14 grab feature, for some reason now it's hard to stop grabbing entities

**Comment by hsjdhudn** [comment]
> > emm,You mean, you can get the development version without being a sponsor, but how? As for the entity that is difficult to give up grabbing, what does it mean? [Doubt]
> > > wdym, u don't need to be a patron in patreon to get the dev version
> > 
> > 
> > > also its hard to let go of grabbed entities (especially if you're trying to do that after entering and exiting suit mode)
> 
> use gradlew.bat (download source code, open cmd prompt, go to the source code folder, enter "gradlew.bat build"
> 
> 0.14 grab feature, for some reason now it's hard to stop grabbing entities
> 
> i think the ability to give control to entities (npcs) should be disabled

e.........
![2279e0237bf4a6e04f2817c871b3ef52](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/159747651/6274d8f6-d982-4f77-b3c0-c6260628d8fd)

**Comment by spacedan228** [comment]
> e......... ![2279e0237bf4a6e04f2817c871b3ef52](https://private-user-images.githubusercontent.com/159747651/311423406-6274d8f6-d982-4f77-b3c0-c6260628d8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzcyMjUsIm5iZiI6MTcwOTk3NjkyNSwicGF0aCI6Ii8xNTk3NDc2NTEvMzExNDIzNDA2LTYyNzRkOGY2LWQ5ODItNGY3Ny1iM2MwLWM2MjYwNjI4ZDhmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwOTM1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODlmOTFhMzliN2E1ODM2NDBmMGRmNWUwODkzMWM2MWNiZDJjZWJiNjQ3ZmYxYThkOTJkMDQ3YTFhYjdmZjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2FtyyXA7lbGQUeaWSwVdHNDhjuTOQbBBtBf-oe8KKso)
have you unzipped the folder

**Comment by spacedan228** [comment]
have you unzipped the folder

**Comment by spacedan228** [comment]
u need to go to source code folder in cmd and enter "gradlew.bat build"

**Comment by hsjdhudn** [comment]
> have you unzipped the folder, also why are u in that folder, use cd to go to a folder or cd../cd .. to go to the previous folder, use dir to view files in the current folder
Insufficient memory [crying], send it directly [I have to be helpless]

**Comment by hsjdhudn** [comment]
> > have you unzipped the folder, also why are u in that folder, use cd to go to a folder or cd../cd .. to go to the previous folder, use dir to view files in the current folder Insufficient memory [crying], send it directly [I have to be helpless]

The memory used for building is insufficient [alas] {not storage}, so please.

**Comment by LtxProgrammer** [comment]
0.14 is still under massive technical decisions. Please refrain from submitting issues until the features are more fleshed out.
