### ISSUE TITLE
additional lights and changed mod cause a conflict of some type

### ISSUE THREAD

**Issue by cheapskate82** [LtxProgrammer/Changed-Minecraft-Mod#791]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/159492087/b970aedf-93fc-4ad1-997e-aded34e67d7b)
[latest.log](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/14439722/latest.log)
i attempted to start up a modpack after adding the changed mod to it, and it conflicted with the "addtional lights" mod

**Comment by LtxProgrammer** [comment]
Seems that the latex covered block logic is applying too early in the mod loading process.
