### ISSUE TITLE
A 0.14 bug on start

### ISSUE THREAD

**Issue by alexbomb6666** [LtxProgrammer/Changed-Minecraft-Mod#796]
Funny bug that doesn't even let me to into the main menu, client crashes all the time
[crash-2024-02-29_14.09.03-client.txt](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/14447175/crash-2024-02-29_14.09.03-client.txt)

**Comment by LtxProgrammer** [comment]
`changed:dark_latex_wolf_partial#main` failed to register, it must of thrown an exception. Could you send the whole log?

**Comment by LtxProgrammer** [comment]
Stale
