### ISSUE TITLE
suit issue

### ISSUE THREAD

**Issue by crazydave19899** [LtxProgrammer/Changed-Minecraft-Mod#798]
Version 0.14 grab suit mode does not allow you to release entity, instead it allows the entity to control you.

**Comment by alexbomb6666** [comment]
> Version 0.14 grab suit mode does not allow you to release entity, instead it allows the entity to control you.

You should check out what holding the ability button does instead of clicking on it

**Comment by crazydave19899** [comment]
I tested it.

**Comment by LtxProgrammer** [comment]
Not an issue, grab actions are explained when you grab/suit something

**Comment by crazydave19899** [comment]
How do you remove remove the entity in suit mode?

**Comment by spacedan228** [comment]
hold Z while "grab" is selected

> How do you remove remove the entity in suit mode?
