### ISSUE TITLE
[v0.14] Player's heads will spin 360° in inventory rendering as a transfur animation plays.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#800]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/991c853e-4993-49ee-ad7e-b07e355fcc52

**Comment by LtxProgrammer** [comment]
Lol, freaky. Looks like it's synced with how the animation is lerp-ed onto the head rotation. I bet the inventory model's head is rotated 360 already when rendered, so it lerps back to 0.
