### ISSUE TITLE
Turned entities glich?

### ISSUE THREAD

**Issue by LatexGlovesEater** [LtxProgrammer/Changed-Minecraft-Mod#81]
idk if this happens with all turned mobs 
[Video_2022_12_06-2.webm](https://user-images.githubusercontent.com/119748930/206045216-d11b34a4-a83d-4a6c-858c-35b4a9f991a3.webm)

**Comment by LtxProgrammer** [comment]
That's from the cake monster's default behavior. I'll fix it.
