### ISSUE TITLE
Villagers Will Run From Transfurred Players That Aren't In their Line Of Sight.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#810]
This Inconsistency Has Existed For A Long Time, But I have finally acknowledged this issue,

NPC goo beasts don't cause nearby villagers to flee unless they are in the Villager's direct line of sight, The same goes for zombies,
Transfurred players will cause villagers to flee regardless of if the villager can see them or not.

https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/bdc80283-55cf-4eb2-b0bb-7812c26e5107

**Comment by Anonogon** [comment]
This could easily be fixed by making villagers not afraid of transfur players.
