### ISSUE TITLE
Adapt to Create Mod

### ISSUE THREAD

**Issue by Zhusiyuan354** [LtxProgrammer/Changed-Minecraft-Mod#811]
Allow to put the latex liquid into Item Drain and Fluid Tank. Maybe this's a very tiny feature I think is important:}

**Comment by spacedan228** [comment]
i think you can do that already, test before posting

**Comment by Zhusiyuan354** [comment]
> i think you can do that already, test before posting

I 've already test! Create Mod version is 0.5.1g,click the Item Drain the latex bucket just jumped away!
