### ISSUE TITLE
Missing part of the source code build module

### ISSUE THREAD

**Issue by hsjdhudn** [LtxProgrammer/Changed-Minecraft-Mod#815]
ltx, I downloaded the v 0.14 dev source code from you and built the module, but there was a problem at startup, showing that the code was missing. I saw from the compressed viewer view module that part of the json didn't convert to class, and I don't know if it's my computer, Or the source code itself is a problem, or a third party, so let me see, you also check, OK?
![Screenshot_2024-03-14-17-48-31-901_com tungsten fcl](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/159747651/f954a0b3-2b64-4ef2-8762-37564256c988)

**Comment by hsjdhudn** [comment]
[Uploading crash-2024-03-14_17.48.19-client.txt…]()

**Comment by LtxProgrammer** [comment]
`LatexVariant` was renamed to `TransfurVariant` in 0.14. If you are attempting to run 0.14 with any mod that depends on the changed mod, it will break. For example: foxyas' Changed plus.

**Comment by hsjdhudn** [comment]
thank you（happy）
