### ISSUE TITLE
General inconsistencies

### ISSUE THREAD

**Issue by DeviousSlugcat** [LtxProgrammer/Changed-Minecraft-Mod#821]
Quark emotes, Not Enough Animations, Supplementaries, and other player animation mods don't appear on transfurred players. (Which is more inconsistent than a problem)
Squid dogs do this thing where seemingly out of nowhere they'll start jittering violently (As far as I know they're the only ones that do this) https://files.catbox.moe/33wyfv.mp4

**Comment by DeviousSlugcat** [comment]
The only reason I bring up player animations is that some mods that require those animation mods e.g: first-person model requires Not Enough Animations for working first-person maps and such.

**Comment by LtxProgrammer** [comment]
Not enough anims was already made compatible for 0.13.1

**Comment by LtxProgrammer** [comment]
Any other animation mod needs to be manually studied for implementing compatibility, and thus, would not apply automatically since the transfers are using their own animator.

**Comment by LtxProgrammer** [comment]
I think I fixed the jittering while swimming issue already in 0.13.1, but I'll double check.

**Comment by LtxProgrammer** [comment]
Jitter was fixed in 24873da5d4d492b834c2581ccb1c57209c3cef87
