### ISSUE TITLE
NotEnoughAnimations breaks new Centaur model

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#835]
Hind legs don't render.
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/100542617/0540275b-4fb3-4919-a8fe-6d1da3bbc796)

**Comment by LtxProgrammer** [comment]
They're rendering on the front half of the model.

**Comment by LtxProgrammer** [comment]
Fixed with 02060178
