### ISSUE TITLE
Centaur related issues

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#836]
Because making 3 seperate issues is kinda pointless...
## Opinion

- The centaur hitbox should be reduced to 2x2, navigating forests are hard.
- The camera off-set should only be in third-person, as it makes the camera weird to turn in first-person.

## Bugs

- The crawling animation is broken/weird (bijimio screenshot)
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/100542617/f485c873-aaed-47de-8e4a-7abc7307577a)

**Comment by LtxProgrammer** [comment]
For the hitbox, I was considering making leaves have no collision from the bottom, but other mods already do this. The player can also set their size to the minimum to be small enough.

Disabling the camera offset in first person would break the first person mod visuals.

**Comment by bijimio** [comment]
it appears even at minimum size, the centaur is still incabable f fitting through 2 block spaces without crouching

https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/2a5ca799-32c9-4d02-9093-6eaa2b32247d
