### ISSUE TITLE
Player Capes Don't render on Goo Beasts.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#837]
This has been a long-time missing feature, capes wont render on latex humans either (originally noticed by Yird)

**Comment by Y1rd** [comment]
I don't think it would be too hard to add this onto the humanoid like latex creatures, however...
Centaur, Dark Latex Pup, etc, would be more complex.

**Comment by LtxProgrammer** [comment]
I remember why I didn't originally add the cape layer. It was because the cape model is baked into the default player model, whereas the beasts didn't have one in their model. I can fix this by creating a cape model, and have it align with the entity's torso.

**Comment by LtxProgrammer** [comment]
In addition, it would be the same for the centaur as it is for the other entities. And I'll just not give the pup a cape.
