### ISSUE TITLE
Human goo beast NPCs with a player's skin that transfur another entity will default to Alex or Steve.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#838]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/e8a80716-e3c0-4c11-84f8-6448dfb4ee59

**Comment by Y1rd** [comment]
Should've been a white latex wolf smhhh
Okay but I kinda want it to be a option.

**Comment by LtxProgrammer** [comment]
I had apparently wrote code for this specific situation 
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/106349281/467a2d3c-247b-410b-a32c-4ce8d7200b2f)
I don't remember why though.
