### ISSUE TITLE
Transfurred Players will stutter when moving against a wall

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#840]
Hitbox probably should stay as the normal size.

**Comment by LtxProgrammer** [comment]
Is this while you drag the slider, or when you exit the BPI menu?

Also the hitbox size difference is negligible.

**Comment by Y1rd** [comment]
> Is this while you drag the slider, or when you exit the BPI menu?
> 
> Also the hitbox size difference is negligible.

When you exit the menu after changing your size.
But since the hitbox is only different on the client, the server will teleport you back if you try to fit under spaces that you wouldn't be able to normally.

**Comment by LtxProgrammer** [comment]
I was not able to replicate this bug. Please provide a video showcasing how you caused this.

**Comment by Y1rd** [comment]
When I get a chance later I will.

**Comment by Y1rd** [comment]
@LtxProgrammer 
Okay, this doesn't seem to a hitbox size related issue, it appears to be something wrong with entity collision/hitbox with *any* transfurred player in general.
If moving against a wall, the camera and player will stutter (also why is the latex human hitbox larger? Can't fit under a slab).

https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/100542617/a177abeb-d8ce-4485-b365-222125eb123a

**Comment by LtxProgrammer** [comment]
Bijimio was able to replicate this bug in the dev environment. He set the BPI size to < 100%, and walked into a wall. I am still unable to replicate it consistently myself.

**Comment by LtxProgrammer** [comment]
I think I found it. Bug seems to occur when the player `esc`'s out of the BPI screen. Reviewing the code shows that the BPI packet only sends when the player clicks "Done"
