### ISSUE TITLE
Changed: MC Mod v0.13.1 doesn't work with OptiFine

### ISSUE THREAD

**Issue by Turanus5966** [LtxProgrammer/Changed-Minecraft-Mod#861]
When I try to run Changed: MC Mod v0.13.1 with OptiFine, game crashes.

**Comment by Turanus5966** [comment]
[message.txt](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/15001718/message.txt)

**Comment by LtxProgrammer** [comment]
I will not be adding compatibility with Optifine. I'd recommend using Rubidium and Oculus instead.
