### ISSUE TITLE
V0.14 (unreleased) KeepForm and TF Progress UI doesn't work

### ISSUE THREAD

**Issue by kohtalee0910** [LtxProgrammer/Changed-Minecraft-Mod#863]
Keepform doesn't keep your variant when you die, and the progress overlay doesn't show

**Comment by LtxProgrammer** [comment]
Progress overlay was intentionally removed, and will be reverted back to the old kind of progress bar (A dang-ometer). As for the keepform, it may stem from the check to the `willSurviveTransfur` property, which may have somehow defaulted to false.

**Comment by LtxProgrammer** [comment]
Should be fixed with 6dfbd9a3e9d582d16fdcbb4a4bb6b75daa1629c3
