### ISSUE TITLE
Compatibility: playerAnimator with Better Combat and MrCrayfish's Gun Mod with addons (Animations)

### ISSUE THREAD

**Issue by MortemFoE** [LtxProgrammer/Changed-Minecraft-Mod#869]
For now transfurred players doesn't have animations from playerAnimator and Better Combat mods. In first person view camera goes for a brief moment inside transfurred player's head each time the said player "swings" any weapon with modded animations (Only the weapon itself moving as intended by those mods) which makes the close combat almost unplayable. As a temporary solution to the problem i'm using First-person Model mod.

As for MrCrayfish's Gun Mod and addons - transfurred players doesn't have animations when they holding a gun or aiming with it but only in third person view and for other players. In vanilla first person view all animations work as intended.

**Comment by Hidden44** [comment]
Confirming both statements.
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/98447510/3c75591d-031c-422b-b765-d5005e4183cd)

**Comment by LtxProgrammer** [comment]
Added animation compatibility with CGM a8c2a5ba75368514b7a8b0412ee9ca90c9c59314
