### ISSUE TITLE
Create mod compatibility

### ISSUE THREAD

**Issue by NormalButTalkingBee** [LtxProgrammer/Changed-Minecraft-Mod#873]
Whenever i try to load in the changed mod with Create, it always crashes, is this a bug for everyone or am i forgetting something?

![Screenshot 2024-04-28 203911](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/168004283/135b0df3-ca01-4426-8e9d-cf16e258b1c9)

**Comment by LtxProgrammer** [comment]
Are you using optifine?

**Comment by NormalButTalkingBee** [comment]
> Are you using optifine?

No

**Comment by gengyoubo** [comment]
Is there a log or something like that?

**Comment by NormalButTalkingBee** [comment]
> Is there a log or something like that?

![Screenshot 2024-05-02 182325](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/168004283/55a3721f-95e5-4f19-9434-74969d419d98)
![Screenshot 2024-05-02 182405](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/168004283/9c7224bb-88b7-47d9-a3d5-4d7d231ae42b)

**Comment by LtxProgrammer** [comment]
The missing model error is not debatable with the crash log. It only happens because an error happened that didn't crash the game (bad mod loading state). This may be because a different mod has a bad fml version. You need to send the `logs/latest.log` right after it crashed.

**Comment by LtxProgrammer** [comment]
As for how I could fix this error in the future (or rather give a better crash log), I'll be digging into the renderer registry code.

**Comment by bobby2411** [comment]
I'm having similar issues with Optifine...

**Comment by bobby2411** [comment]
Do I need to make a new issue or could it fall under here?

**Comment by gengyoubo** [comment]
You send me the crash log and I either know why.

**Comment by bobby2411** [comment]
well here's the thing, it didn't make a crash log, which is weird imo. I also tested with JUST optifine and this mod, still got the crash...

**Comment by bobby2411** [comment]
Also Create isn't crashing for me, which is extremely weird.(Then again I'm using v0.13.1)

**Comment by gengyoubo** [comment]
I was wondering what modules you have installed?

**Comment by bobby2411** [comment]
Well I disabled any other mods I had, and was able to confirm that Optifine is what's crashing my game.

**Comment by bobby2411** [comment]
And it's not generating a crash log either, still don't know why.

**Comment by gengyoubo** [comment]
What is the version of Optifine?

**Comment by gengyoubo** [comment]
I've installed it with Optifine before, but it doesn't seem to crash!

**Comment by gengyoubo** [comment]
This version might work?
[optifine.zip](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/15195495/optifine.zip)

**Comment by bobby2411** [comment]
> What is the version of Optifine?

Well I'm using the latest version of 1.18.2's optifine so...

**Comment by gengyoubo** [comment]
Did what I sent you work?

**Comment by LtxProgrammer** [comment]
Don't use optifine, please use embeddium/rubidium and oculus. Optifine is only good for vanilla Minecraft, it sucks at being compatible with mods.

**Comment by MortemFoE** [comment]
Optifine in latest versions of minecraft is also useless - it is breaking mods, making really low performance gain, changing the code of the game in unknown way, is closed source project... It's good for minecraft 1.12.2 or lower i think, but for 1.18.2 i'd recommend embeddium and other mods for performance which are mostly compatible with anything. In minecraft 1.20.1 or later optifine crashes the game itself without any other mods as i heard.

**Comment by LtxProgrammer** [comment]
This crash is typically from a missing dependency or a bad mod/mod loader version. The given error is terrible at explaining this. What actually causes this error, is the mod loading environment is `"Cowardly refusing to send event FMLCommonSetupEvent to a broken mod state"`.

The order of events is as follows:

1. `EntityRenderersEvent.RegisterLayerDefinitions` is sent to event listeners
2. `EntityRenderersEvent.RegisterRenderers` is sent to event listeners
3. Somewhere a check fails, and events sent afterwards are refused
4. `FMLCommonSetupEvent` is sent to event listeners

The layer definitions were registered on the `FMLCommonSetupEvent`, thus causing the definition to be missing when the event is never sent. I have fixed the layer definition code to now listen to `EntityRenderersEvent.RegisterLayerDefinitions` in eed8db6c66c66dcd12a5b8a7f1d34b6202cc6338. While this wont fix the incompatibilities that are present when loading, but the mod loader will be able to provide a more accurate report.

Currently the best fix for users experiencing this issue, is to validate that Minecraft will launch without Changed in their modpack.
