### ISSUE TITLE
How to use this command?

### ISSUE THREAD

**Issue by onodearayuta** [LtxProgrammer/Changed-Minecraft-Mod#874]
Could I ask a question please, I don't know where to ask the question?
/gamerule changed:fusabilityDurationPlayer ture/false
How to use this command? And If I use this command, what happen? Could you give some examples?

**Comment by LtxProgrammer** [comment]
The issues page here is not a place to ask questions about the mod. It's for reporting issues the mod has or with other mods.

To answer your question though, that gamerule is not a true/false rule, but an integer rule. It's how many ticks after the player is TF'd that they're able to fuse for (e.g. Shark + Shark, Light latex wolf + light latex knight).

If you have any other questions, please ask them in the Discord.
