### ISSUE TITLE
Invalid command

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#875]
About this command.
/gamerule changed:fusabilityDurationPlayer (value)
No amount of changing its value will change the amount of time a latex player is allowed to fuse.
The specific phenomenon is that fusion is also possible regardless of tuning to numbers (including 0).

https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/113955003/d5f2b097-ccef-4547-a512-cc15d0fb8fe9

Please let me know if there is a problem with my operation.

**Comment by LtxProgrammer** [comment]
I forget that the client doesn't sync gamerules from the server.
