### ISSUE TITLE
Carry On Mod Extra Arms

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#889]
When carrying a block With the carry on mod as a latex, the player's normal human arms will be rendered.
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/0cefa77a-d565-4896-9df8-ff4aeeb95766)

**Comment by LtxProgrammer** [comment]
Ah, this one was posted before (#785). I had attempted to fix it, but was unable to.
