### ISSUE TITLE
IV rack and latex pillar have lighting issue

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#89]
![2022-12-08_22 14 02](https://user-images.githubusercontent.com/117211742/206637117-95907b26-ec8a-49ab-91d7-9a13e17fefae.png)

**Comment by asweqr** [comment]
this is something i noticed that would tend to happen with smooth lighting enabled

**Comment by asweqr** [comment]
![image](https://user-images.githubusercontent.com/89364836/206882319-0323d2e6-74bc-4391-810c-e8a97f5497bd.png)
before smooth lighting
![image](https://user-images.githubusercontent.com/89364836/206882325-5a512620-39fc-4e15-b626-fe6fdd5a0930.png)
after enableing smooth lighting
