### ISSUE TITLE
When entering a chest contaminated by latex it will sometimes uncontaminate the state.

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#905]
Check out this video for details

https://www.bilibili.com/video/BV1eJ4m1N7jm/?spm_id_from=333.337.search-card.all.click&vd_source=686394728da821f4c2d652bbab263b5b

**Comment by LtxProgrammer** [comment]
Should be fixed in 2df4d06b94444ce77cbfb908a3736a60e65c6dab
