### ISSUE TITLE
Is he standing, or is he lying down?

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#907]
In his own mind, he was standing. But to others, his behavior is swimming.
[[https://www.bilibili.com/video/BV13w4m1D7Y9/?buvid=Y34FA53A319DF5584A5CB5B00CF65B847F33&from_spmid=search.search-result.0.0&is_story_h5=false&mid=0VZTtOKQZi8tsoIwYGQeGw%3D%3D&p=1&plat_id=116&share_from=ugc&share_medium=iphone_i&share_plat=ios&share_session_id=9702F10A-3DA1-422A-92DC-6FA3E77C9978&share_source=COPY&share_tag=s_i&spmid=united.player-video-detail.0.0&timestamp=1716117918&unique_k=MtFIEzu&up_id=1662014004&vd_source=686394728da821f4c2d652bbab263b5b](url)](https://www.bilibili.com/video/BV13w4m1D7Y9/?buvid=Y34FA53A319DF5584A5CB5B00CF65B847F33&from_spmid=search.search-result.0.0&is_story_h5=false&mid=0VZTtOKQZi8tsoIwYGQeGw%3D%3D&p=1&plat_id=116&share_from=ugc&share_medium=iphone_i&share_plat=ios&share_session_id=9702F10A-3DA1-422A-92DC-6FA3E77C9978&share_source=COPY&share_tag=s_i&spmid=united.player-video-detail.0.0&timestamp=1716117918&unique_k=MtFIEzu&up_id=1662014004&vd_source=686394728da821f4c2d652bbab263b5b)

**Comment by gengyoubo** [comment]
> 在他自己的脑海中，他是站着的。但对其他人来说，他的行为是游泳。 [<iframe src="//player.bilibili.com/player.html?isOutside=true&aid=1104745683&bvid=BV13w4m1D7Y9&cid=1543866043&p=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"></iframe>](url)

**Comment by LtxProgrammer** [comment]
How did you encounter this issue, what did you do?

**Comment by gengyoubo** [comment]
> How did you encounter this issue, what did you do?

Bug that happens when using white latex wolf

**Comment by LtxProgrammer** [comment]
What were you doing when this happened?
