### ISSUE TITLE
[Dev Bug] Self-Drawn Goo Syringes Will Always Default to Special Latex.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#911]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/79c20336-9f56-4a0a-9cc3-71497465f3d0

**Comment by gengyoubo** [comment]
Uh, I'll make a digression. How do I upload my own special latex into this mod?

**Comment by LtxProgrammer** [comment]
> Uh, I'll make a digression. How do I upload my own special latex into this mod?

This is discontinued. Maintenance on old models to fit the new system and creating new ones for patrons was too much work.
