### ISSUE TITLE
Some Latex Forms Have Broken / Misaligned Arms While Using Carry On.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#917]
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/1f993ef4-d0c7-46c5-ae06-a362c089e10b)
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/a5219405-3cf5-49eb-8196-0dd6be8e58e3)
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/10f9beae-4521-4bd6-b560-ca3b1e22a5f8)
![image](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/117211742/c9c1cf0b-7872-456a-950c-038936dbbfa9)
not to mention the armor Layer is not aligned with the arms either,
I wonder if it is possible to instead create a animator for carry on to apply to the arms, as well as a held block offset for forms like the centaur?

**Comment by LtxProgrammer** [comment]
You're right about the animator idea, I designed to be as close to the original mod as possible (as badly implemented as the original is). I'll start work on that.
