### ISSUE TITLE
Armor is broken on 3-block tall transfurs

### ISSUE THREAD

**Issue by REDUX4** [LtxProgrammer/Changed-Minecraft-Mod#918]
![2024-05-31_15 29 06](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/119761192/1334a6ca-92c0-492e-a6f5-526c03efd05a)

**Comment by LtxProgrammer** [comment]
This issue will be fixed when the sharks get remodeled.

**Comment by XIONGCHUMMO** [comment]
The crocdile also has this bug
![屏幕截图 2024-06-20 235722](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/44457978/7af7bf2d-5632-42d9-ac86-ef4f754bc0a9)

**Comment by LtxProgrammer** [comment]
Now fixed for buff sharks.

**Comment by LtxProgrammer** [comment]
These transfurs have now been remodeled.
