### ISSUE TITLE
Incompatibility with Ars Nouveau

### ISSUE THREAD

**Issue by GioMaybeDev** [LtxProgrammer/Changed-Minecraft-Mod#920]
Version of Changed MC: 0.13.1
Version of Ars Nouveau: 2.9.0

**Comment by LtxProgrammer** [comment]
Do you have any crash or related information about the incompatibility?

**Comment by LtxProgrammer** [comment]
Please reopen this issue when you have more information.

**Comment by LtxProgrammer** [comment]
After testing on my own, this issue was already fixed for 0.14.
