### ISSUE TITLE
Beyond Earth armors still cause crashes

### ISSUE THREAD

**Issue by spacedan228** [LtxProgrammer/Changed-Minecraft-Mod#923]
[latest.log](https://github.com/user-attachments/files/15545720/latest.log)

P.S. I used the latest version of Beyond Earth (7.0), trying to use 6.2 crashes the game at loading.

**Comment by spacedan228** [comment]
and yes, i used the last 0.14 build

**Comment by LtxProgrammer** [comment]
What did you do to cause the crash?

**Comment by spacedan228** [comment]
> What did you do to cause the crash?

wore the spacesuit

**Comment by spacedan228** [comment]
[latest.log](https://github.com/user-attachments/files/15570737/latest.log)
this happens when i try to launch the game with Beyond Earth 6.2

**Comment by LtxProgrammer** [comment]
`6.2` crashes because I mis-configured the mixin remap (since it was a minecraft render function).
`7.0` crashes because it renames both the model's class.
