### ISSUE TITLE
Can a mechanic be added?

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#924]
Since players can enable the ‘retain consciousness during transfur’ rule so that they can retain consciousness during transfur and gain the traits of the variant instead of dying, can a similar mechanic be added for the original mc human npc's (e.g. the original villagers, wandering merchants, marauders, etc.)? ? (e.g. original villagers have a probability of retaining consciousness after being transfur, when only their model is changed without affecting their AI (e.g. trading, career system, etc.))
![屏幕截图 2024-06-03 181112](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/113955003/3e7a72da-9eeb-4350-b285-f9dae6854153)

**Comment by spacedan228** [comment]
that'd be interesting but probably hard to implement

**Comment by spacedan228** [comment]
so maybe it'd be cool if there were already transfurred (and ofc conscious) villagers, it would make sense if they were tf'd into "organic"/non-latex forms

**Comment by gengyoubo** [comment]
What he means is to add rules to human NPCs like villagers that are similar to the player's "gamerule keepConscious" game rules, such as "gamerule keephumannpccomscious < number>(%)"

**Comment by gengyoubo** [comment]
It means that every time you get transfurred there is <number>% will you lose consciousness.

**Comment by spacedan228** [comment]
i think you meant "they"
