### ISSUE TITLE
Latexes in space

### ISSUE THREAD

**Issue by spacedan228** [LtxProgrammer/Changed-Minecraft-Mod#926]
when they spawn in Beyond Earth dimensions, they quickly die and respawn again, causing lag
![2024-06-05_19 37 32](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/e00e4513-e1b3-491a-b874-ce9e74b523cb)
![2024-06-05_19 36 35](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/483723c2-5c81-44c1-bb68-095339b92aa4)

**Comment by LtxProgrammer** [comment]
Would it make sense for the latex alien to be able to survive on the other planets? I was thinking about it while writing a fix for the spawning issue.

**Comment by LtxProgrammer** [comment]
> Would it make sense for the latex alien to be able to survive on the other planets? I was thinking about it while writing a fix for the spawning issue.

This was added as an optional feature with datapacks in 88ba8c03882196995ed313607e38628cd210bfdc
