### ISSUE TITLE
Sometimes absorbing a suited mob causes the mob to appear, invisible

### ISSUE THREAD

**Issue by spacedan228** [LtxProgrammer/Changed-Minecraft-Mod#927]
![2024-06-06_13 48 57](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/150387227/399d82f2-eab0-4c40-ae57-d6de40ae58f1)
(on screenshot there is an arrow that apparently appeared out of nowhere)
the log does not say anything about it

**Comment by LtxProgrammer** [comment]
What mob was it, and was there any special tags to it?

**Comment by spacedan228** [comment]
> What mob was it, and was there any special tags to it?

it was a pillager, but it happens with any humanoid mobs, like witches, skeletons, etc.

**Comment by LtxProgrammer** [comment]
I suspect it's a desync from client-server, the client thinks it has absorbed the target, but the server says otherwise.
