### ISSUE TITLE
Crash when loading All The Mods 7 modpack with Changed mod + Addon

### ISSUE THREAD

**Issue by Razoozle** [LtxProgrammer/Changed-Minecraft-Mod#928]
I have no idea how to read crash logs. Can somebody help me diagnose the incompatibility or problem?

[crash-2024-06-06_11.13.38-client.txt](https://github.com/user-attachments/files/15685444/crash-2024-06-06_11.13.38-client.txt)

**Comment by LtxProgrammer** [comment]
At the top of the crash log "OutOfMemory". It crashed because it ran out of memory for the game. Please look into the client config for changed in your games config directory.
