### ISSUE TITLE
model loading in multiplayer

### ISSUE THREAD

**Issue by ErasylTheGlitch** [LtxProgrammer/Changed-Minecraft-Mod#93]
so... transfur models dont load now, not only in nether but also in overworld, killing urself doesnt work anymore, dont exactly know if this is a modpack issue or mod issue, but plz look into it

**Comment by LtxProgrammer** [comment]
This doesn't seem to occur with just changed. What other mods are you using?

**Comment by ErasylTheGlitch** [comment]
note that it only happens when multiple people are online btw

**Comment by LtxProgrammer** [comment]
well that's gonna be tricky to debug
