### ISSUE TITLE
Several dark Latex Pup Issues.

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#935]
- [x] Dark Latex Pup Players' puddle ability is not able to be used.

- [x] Dark Latex Pup Players are capable of transfurring with an empty hand.
 
- [x] Dark Latex Pup Players are capable of grabbing and absorbing entities.

- [ ] The Eye Layer Of Dark Latex Pups In Puddle Mode don't match with the model and appear to float.

- [x] Dark Latex Pup AI will not work properly when leashed, causing them to run around super fast uncontrollably.

**Comment by gengyoubo** [comment]
Regarding the question “Dark Latex Pup Players' puddle ability is not able to be used.”
Is it possible that the model just doesn't show up, but still has a slow effect attached to the entity?

**Comment by gengyoubo** [comment]
> 关于“Dark Latex Pup Players's puddle ability is not be used”的问题。有没有可能模型只是没有显示，但仍然对实体有缓慢的效果？

In version 0.13.1, the slow effect is now attached to entities normally, even though the model doesn't show it.
