### ISSUE TITLE
No model for layer of a tf

### ISSUE THREAD

**Issue by FlashModding** [LtxProgrammer/Changed-Minecraft-Mod#947]
Error: java.lang.IllegalArgumentException: No model for layer changed:dark_latex_wolf_partial#main is the error

**Comment by gengyoubo** [comment]
#943

**Comment by gengyoubo** [comment]
`dark_latex_wolf_partial#main`这个bug已经修复，但是我想知道是什么bug能引起这个bug?

**Comment by gengyoubo** [comment]
请发一下日志或崩溃日志（原因并不在'dark_latex_wolf_partial#main'上）

**Comment by gengyoubo** [comment]
在#943中查明，是某些启动上的bug引起了模型bug。

**Comment by gengyoubo** [comment]
并且修复了这个问题，但是我需要知道是什么引起了这个bug,换一句话说是bug源在哪？

**Comment by gengyoubo** [comment]
> 错误：java.lang.IllegalArgumentException：没有更改图层的模型：dark_latex_wolf_partial#main 是错误的

所以单发这个是找不到原因的

**Comment by gengyoubo** [comment]
#943 is not the source of the bug, please provide crashreport and logs

**Comment by gengyoubo** [comment]
By the way, this modeling bug is fixed in https://github.com/LtxProgrammer/Changed-Minecraft-Mod/commit/97f762aaec171661b3009d008cbcf60e22bb990a

**Comment by FlashModding** [comment]
Nice
