### ISSUE TITLE
Incompatible with OptiFine

### ISSUE THREAD

**Issue by NickTheWickerbeast** [LtxProgrammer/Changed-Minecraft-Mod#948]
OptiFine causes minecraft to crash with the Changed mod. I'm using the latest version of 1.18.2 OptiFine (1.18.2_HD_U_H9), and I'm using the latest version of the Changed mod (v0.13.1). I don't recall this being an issue in the past two versions I've played: v0.11.3 and v0.12b.

**Comment by spacedan228** [comment]
optifine is not and will not be supported, some other mods have the same issue, but it cannot be fixed

**Comment by szpigozzzzz** [comment]
i did a suggestion a while ago that optifine was crashing the changed mod,and it was fixed (i do not remember which version of the mod it was,but i can confirm it got fixed)

the optifine problem is a "will not fix" problem,i suggest sticking to embeddium,a forge port of sodium
