### ISSUE TITLE
New gamerule

### ISSUE THREAD

**Issue by gengyoubo** [LtxProgrammer/Changed-Minecraft-Mod#953]
/gamerule NoNeedToSwitchControl true/false
When if a player who is in a post-Transfur situation combines with a regular player, can 2 or more players directly control 1 without switching body control? (False is that physical control is still required, True is that multiple players can directly control one character.)
/gamerule IsItPossibleToEscape true/false
Whether an entity can be escaped when caught by latex
/gamerule MaximumPlayersCanBeFused 2 (number）
When if a player who is in a post-Transfur situation combines with a regular player, the maximum number of regular players that can be combined.
/gamerule ResurrectionInTheSameStateAsBeforeDeath true/false
If a player who is in a post-Transfur state is bonded to a regular player, does the player remain bonded to the regular player even if the regular player dies and is revived, instead of being initialized (False is not bonded, True is bonded).

**Comment by gengyoubo** [comment]
![屏幕截图 2024-06-25 222631](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/113955003/f21a2b79-a36f-49e3-93f6-32aa9d2bc969)
![屏幕截图 2024-06-25 222626](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/113955003/41d28658-7fcd-4491-8f9b-118b41d71bf3)

**Comment by cecnull1** [comment]
中文：为了方便复制粘贴以及查看，我以文本形式发出。
English: To facilitate copying and pasting as well as viewing, I am sending it in text form.

当如果处于已Transfur后的玩家与普通玩家结合时，是否可直接2个或以上的玩家控制1个，而无需切换身体控制权？（False 为 仍需身体控制权，True 为 多个玩家可直接控制一个角色。）

当如果处于已Transfur后的玩家与普通玩家结合时，能够最多结合普通玩家的数量。

当如果普通玩家被胶兽（或已Transfur的玩家。共同前提是 存在兽化技能）感染时，是否立即直接非法Transfur化，而不是达到阈值？（False为达到阈值触发，True为直接触发。）

当如果处于已Transfur后的玩家与普通玩家结合时，是否即便普通玩家死亡，复活后还是保持与之结合状态，而不是被初始化（False 为 不保持，True 为 保持。）

当如果处于已Transfur后的玩家与普通玩家结合时，是否同步其所有属性，但不包括UUID（这一点很重要）？（True 为 同步，False 为 不同步）

当如果处于已Transfur后的玩家与普通玩家结合时，普通玩家是否能够在这种情况下挣脱?（False为无法挣脱, True为可挣脱。）

**Comment by spacedan228** [comment]
1. it would not work well
2. why should that be a gamerule, maybe only for mobs
3. it would be just unrealistic for a latex to have more than one host
4. no

**Comment by cecnull1** [comment]
> 1. it would not work well
> 2. why should that be a gamerule, maybe only for mobs
> 3. it would be just unrealistic for a latex to have more than one host
> 4. no

之所以我让他实现，是因为我喜欢这样添加游戏规则，喜欢我的想法。如果开发者不愿意开发，那我自己开发一个。

I let him implement it because I like adding game rules and my ideas. If the developer is not willing to develop, I will develop one myself.

**Comment by cecnull1** [comment]
> 1. it would not work well
> 2. why should that be a gamerule, maybe only for mobs
> 3. it would be just unrealistic for a latex to have more than one host
> 4. no

而且我选择的是 怪物 与 玩家 都通用，因此你不应该限制它。

And I chose the monster and player are universal, so you should not limit it.

（This is purely a Baidu machine translation. If there are any errors, please correct them）

**Comment by spacedan228** [comment]
a player having more than one player suited would just be completely unrealistic (cuz there's physically only place for one)

both players being able to control at the same time would not work

**Comment by cecnull1** [comment]
> a player having more than one player suited would just be completely unrealistic (cuz there's physically only place for one)
> 
> both players being able to control at the same time would not work
> 
> also as you probably know, gengyoubo is mostly just a translator like me

游戏规则可以实现想法，你不想要也可以改为默认值，而不是删除游戏规则。因为我真的很需要这些规则。

The game rules can implement ideas, and you can change them to default values if you don't want them, rather than deleting the game rules. Because I really need these rules.

**Comment by cecnull1** [comment]
说明一下：我喜欢发原文和翻译后的文字，这样子会更容易理解，而不是再翻译回来。

Explanation: I prefer to post the original text and the translated text, as it is easier to understand, rather than translating it back.

**Comment by cecnull1** [comment]
总之：不喜欢规则可以改为默认值，而不是请求删除，因为对特定玩家的需求很重要。

In short, if you don't like the rules, you can change them to default values instead of requesting deletion, as the needs of specific players are important.
