### ISSUE TITLE
Compatibility with Iron's Spells 'n Spellbooks amour's

### ISSUE THREAD

**Issue by goldrichman9Modded** [LtxProgrammer/Changed-Minecraft-Mod#954]
For the latex's hen i using the mod i realize the the pants/ chestplate fore any Iron's Spells 'n Spellbooks amour's will look wired and like this 
![Iron's Spells 'n Spellbooks](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/168244776/6a36982c-442e-4f39-9028-ac65fa03b9aa)

https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

**Comment by goldrichman9Modded** [comment]
Just make the amout look the same as the rest of the amour look like. Like iron amour

**Comment by LtxProgrammer** [comment]
> Just make the amour look the same as the rest of the amour look like. Like iron amour , when installing the mod, just like ars nouv

Not as simple as stated. This mod likely uses their own model for their armor, and thus it wont fit changed's entities. Recreating their armor models just to fit changed is too much work for a little QoL.
