### ISSUE TITLE
Compatibility with the Hordes Mod

### ISSUE THREAD

**Issue by AbsoluteJuicer** [LtxProgrammer/Changed-Minecraft-Mod#956]
Hi, I think some change in the path finding logic or mob ai broke the compatibility with the Horde mod.

Changed mod Version: 0.14 (from Git)
the Hordes mod Version: 1.2.3

**How to Replicate:**

1. launch the game with the mods once and go to "${YOUR_MC_FOLDER}\config\hordes\data\hordes\tables\" and create a file called "changed_all.json"

and paste the following
`[
  "changed:light_latex_wolf_female-10-0-0",
  "changed:light_latex_wolf_male-10-0-0",
  "changed:light_latex_wolf_organic-10-0-0",
  "changed:light_latex_knight-10-0-0",
  "changed:light_latex_centaur-10-0-0",
  "changed:headless_knight-10-0-0",
  "changed:light_latex_knight_fusion-10-0-0",
  "changed:latex_crystal_wolf-10-0-0",
  "changed:latex_crystal_wolf_horned-10-0-0",
  "changed:latex_deer-10-0-0",
  "changed:latex_bee-10-0-0",
  "changed:latex_pink_deer-10-0-0",
  "changed:latex_keon_wolf-10-0-0",
  "changed:aerosol_latex_wolf-10-0-0",
  "changed:dark_latex_dragon-10-0-0",
  "changed:dark_latex_wolf_male-10-0-0",
  "changed:dark_latex_wolf_female-10-0-0",
  "changed:dark_latex_pup-10-0-0",
  "changed:dark_latex_yufeng-10-0-0",
  "changed:latex_beifeng-10-0-0",
  "changed:latex_benign_wolf-10-0-0",
  "changed:latex_blue_dragon-10-0-0",
  "changed:latex_blue_wolf-10-0-0",
  "changed:latex_crocodile-10-0-0",
  "changed:latex_fennec_fox-10-0-0",
  "changed:latex_hypno_cat-10-0-0",
  "changed:latex_leaf-10-0-0",
  "changed:latex_squirrel-10-0-0",
  "changed:latex_manta_ray_female-10-0-0",
  "changed:latex_manta_ray_male-10-0-0",
  "changed:latex_medusa_cat-10-0-0",
  "changed:latex_mermaid_shark-10-0-0",
  "changed:latex_moth-10-0-0",
  "changed:latex_siren-10-0-0",
  "changed:latex_snake-10-0-0",
  "changed:latex_mimic_plant-10-0-0",
  "changed:latex_pink_wyvern-10-0-0",
  "changed:latex_pink_yuin_dragon-10-0-0",
  "changed:latex_purple_fox-10-0-0",
  "changed:latex_raccoon-10-0-0",
  "changed:latex_red_dragon-10-0-0",
  "changed:latex_red_panda-10-0-0",
  "changed:latex_shark-10-0-0",
  "changed:latex_shark_male-10-0-0",
  "changed:latex_shark_female-10-0-0",
  "changed:latex_sniper_dog-10-0-0",
  "changed:latex_alien-10-0-0",
  "changed:latex_snow_leopard_male-10-0-0",
  "changed:latex_snow_leopard_female-10-0-0",
  "changed:latex_squid_dog_female-10-0-0",
  "changed:latex_squid_dog_male-10-0-0",
  "changed:latex_stiger-10-0-0",
  "changed:latex_tiger_shark-10-0-0",
  "changed:latex_traffic_cone_dragon-10-0-0",
  "changed:latex_translucent_lizard-10-0-0",
  "changed:latex_orca-10-0-0",
  "changed:latex_otter-10-0-0",
  "changed:latex_watermelon_cat-10-0-0",
  "changed:latex_white_tiger-10-0-0",
  "changed:latex_yuin-10-0-0",
  "changed:milk_pudding-10-0-0",
  "changed:shark-10-0-0",
  "changed:white_latex_wolf-10-0-0",
  "changed:phage_latex_wolf_female-10-0-0",
  "changed:phage_latex_wolf_male-10-0-0"
]`

2. then go to "${YOUR_MC_FOLDER}\config\hordes\data\hordes\horde_scripts\", create a file called "changed.json" and paste the following:

`{
	"function": "hordes:set_spawntable",
	"value": [
		"hordes:changed_all"
	],
	"conditions": []
}`
3. in game, type "/spawnHordeWave @p 1 hordes:changed_all" to summon 1 wave; then you will find all spawned changed entities will freeze in place (still attacks if you come into their vicinity)

**Comment by LtxProgrammer** [comment]
This is likely related to the attribute change. Where the movement speed was mapped 1.0 -> 0.1 to match the player.

**Comment by LtxProgrammer** [comment]
After review the hordes mod's source code, I have found that entity speed can be configured by the datapack creator. There is a [spawndata function](https://github.com/SmileycorpMC/The-Hordes/wiki/Horde-Scripts-%E2%80%90-Spawndata-Functions#hordesset_entity_speed-140) that will set the entity's speed in a horde. The Changed entities will need to be configured with a speed of 10.0, instead of 1.0.
Modified example provided by the wiki:
```
{
	"function": "hordes:set_entity_speed",
	"value": 10.0,
	"conditions": []
}
```

**Comment by AbsoluteJuicer** [comment]
Thank you so much!
