### ISSUE TITLE
white latex block <- Any

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#960]
![2024-07-07_13 17 06](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/170391667/11d0851f-f39f-494d-b520-5801e4e0333d)
![2024-07-07_13 17 15](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/170391667/69184126-6493-45bd-9121-91b5e158f938)
![2024-07-07_13 17 17](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/170391667/3552a967-5546-426b-b05d-ad08f7d6fe55)

Trigger condition: When entering the white glue block while in the white glue beast state, and maintaining this state after releasing transfur, in this case, switching to other transfur forms will still maintain this state

触发条件：在处于白胶胶兽的情况下进入白胶块，解除transfur后仍保持这种状态，在这种情况下，切到其他transfur形态还是保持这种状态

Video:

https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/170391667/b0dfbab0-edc0-4e03-8fc9-713d5ec53a83

**Comment by cecnull1** [comment]
我不会英文，所以我基本用机翻

I don't know English, so I basically use machine translation

**Comment by hsjdhudn** [comment]
it is a bug…(guess)(china people too)

**Comment by hsjdhudn** [comment]
it is a bug…(guess) 是个bug…（猜测）

**Comment by LtxProgrammer** [comment]
This behavior isn't inherently a problem, since it is not achievable in survival mode. It can only occur with commands (or with a certain mod..).
