### ISSUE TITLE
you can tame players?

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#961]
https://github.com/LtxProgrammer/Changed-Minecraft-Mod/assets/119010731/f604ae44-105c-4681-88d4-f3211a4328ee

**Comment by DomezTheDragon** [comment]
i think i was the first to stumble upon this bug because of the changed addon, and i told foxyas, and turns out it was base create mod lol

**Comment by cecnull1** [comment]
It's normal, that's not a problem.

**Comment by Foxyas** [comment]
> i think i was the first to stumble upon this bug because of the changed addon, and i told foxyas, and turns out it was base create mod lol

Lol

**Comment by LtxProgrammer** [comment]
There's not much of an issue here, more of an unintended feature. I'll leave this "feature" as a means of RP in multiplayer servers.

**Comment by Foxyas** [comment]
> There's not much of an issue here, more of an unintended feature. I'll leave this "feature" as a means of RP in multiplayer servers.

no way is official lol
