### ISSUE TITLE
issues with partial

### ISSUE THREAD

**Issue by Forensic-Ut** [LtxProgrammer/Changed-Minecraft-Mod#963]
The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: No model for layer 
changed:dark_latex_wolf_partial#main""

How do I fix this

**Comment by Forensic-Ut** [comment]
![Capture22](https://github.com/user-attachments/assets/6394d797-ae6e-4826-b4db-68e8a8319d77)

**Comment by hsjdhudn** [comment]
Friend, you don't have a log, how do we check the complete error

**Comment by LtxProgrammer** [comment]
Related to #943
