### ISSUE TITLE
Conflict with ConnectedTexturesMod module

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#967]
该冲突会导致无法进入Minecraft的世界（存档中包含Mekanism模组中的机器时。估计与任何支持连接纹理的模组都会出问题。）。
如果发生了这种情况，即使删掉CTM，在启动Minecraft时该模组会报错。
必须同时删除在版本文件夹所在的位置中的cache文件夹才能正常启动。

This conflict can lead to an inability to enter the world of Minecraft (when the save file contains machines from the Mekanism mod. It is estimated that any mod that supports connected textures will have problems.).
If this happens, even if you delete CTM, the mod will report an error when you start Minecraft.
The cache folder in the location of the version folder must be deleted at the same time to start normally.

**Comment by cecnull1** [comment]
如果这个漏洞不修复的话，就没法和我朋友一起玩了。

If this vulnerability is not fixed, I won't be able to play with my friends.

**Comment by LtxProgrammer** [comment]
Crash log not provided, so I recreated the issue and got the exception:
```
java.lang.NullPointerException: Cannot invoke "team.chisel.ctm.client.util.BlockRenderLayer.ordinal()" because the return value of "team.chisel.ctm.client.util.BlockRenderLayer.fromType(net.minecraft.client.renderer.RenderType)" is null
```
CTM may be attempting to get a `BlockRenderLayer` from a changed rendertype.

**Comment by cecnull1** [comment]
[crash-2025-06-01_18.23.47-client.txt](https://github.com/user-attachments/files/20539374/crash-2025-06-01_18.23.47-client.txt)
我当初报告问题忘记附上日志了，现在我给了（现在才卡出来）
