### ISSUE TITLE
few things I would like to see fixed

### ISSUE THREAD

**Issue by ensign-labs** [LtxProgrammer/Changed-Minecraft-Mod#975]
1. CPM (Custom Player Models) support
it isn't that important but like I want to see the Goop work properly on models that are not Steve, even if it is just using an RNG for the Goop

2. Quark UI coincidence
I would like to see the button moved to the right side of the pause menu due to Quark's button overlapping

3. tint blocks and not generate new textures for the infected blocks
This is simple but currently with the number of mods I have they use the textures of Items.

4. MAKE SPECIAL LATEX NOT SUMMONABLE WITH COMMANDS (for non-donators)
the special latex crashed my computer twice when messing with it but it was interesting seeing a non-specified latex though.

**Comment by spacedan228** [comment]
just don't craft or try to spawn special latex

**Comment by LtxProgrammer** [comment]
>Quark UI coincidence
I would like to see the button moved to the right side of the pause menu due to Quark's button overlapping

Fixed in ad8d265b3870f11c24ad1f75a87d1249016787fd

>tint blocks and not generate new textures for the infected blocks
This is simple but currently with the number of mods I have they use the textures of Items.

This can be set in the client config with `generateUniqueTexturesForAllBlocks = false`

**Comment by ensign-labs** [comment]
> > Quark UI coincidence
> > I would like to see the button moved to the right side of the pause menu due to Quark's button overlapping
> 
> Now fixed in [ad8d265](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/commit/ad8d265b3870f11c24ad1f75a87d1249016787fd)
> 
> > tint blocks and not generate new textures for the infected blocks
> > This is simple but currently with the number of mods I have they use the textures of Items.
> 
> This can be set in the client config with `generateUniqueTexturesForAllBlocks = false`

oh, Thanks! also strongholds don't spawn in dark latex planes but you don't have to make them spawn if you don't want to though

**Comment by ensign-labs** [comment]
> > Quark UI coincidence
> > I would like to see the button moved to the right side of the pause menu due to Quark's button overlapping
> 
> Now fixed in [ad8d265](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/commit/ad8d265b3870f11c24ad1f75a87d1249016787fd)
> 
> > tint blocks and not generate new textures for the infected blocks
> > This is simple but currently with the number of mods I have they use the textures of Items.
> 
> This can be set in the client config with `generateUniqueTexturesForAllBlocks = false`

So I am having a similar issue now with generateUniqueTexturesForAllBlocks set to false

**Comment by LtxProgrammer** [comment]
What issue are you running into? Is it a crash? Is it memory usage? Or is it only presentation?
I should note that the blocks aren't tinted currently due to rendering technicalities.

**Comment by LtxProgrammer** [comment]
> 1. CPM (Custom Player Models) support
> 
> it isn't that important but like I want to see the Goop work properly on models that are not Steve, even if it is just using an RNG for the Goop

Btw can I get some clarification for what you mean by this? Are you talking about the dripping latex particles?

**Comment by ensign-labs** [comment]
> > 1. CPM (Custom Player Models) support
> > 
> > it isn't that important but like I want to see the Goop work properly on models that are not Steve, even if it is just using an RNG for the Goop
> 
> Btw can I get some clarification for what you mean by this? Are you talking about the dripping latex particles?

well I was talking about the goop texture that covers the player's skin, it's a little funky to see my player be relatively unaffected by the goop

**Comment by ensign-labs** [comment]
> What issue are you running into? Is it a crash? Is it memory usage? Or is it only presentation? I should note that the blocks aren't tinted currently due to rendering technicalities.

Well the Presentation,
It's still taking random textures

**Comment by LtxProgrammer** [comment]
Oh, that sounds like a compatibility issue. What's your modlist?

**Comment by ensign-labs** [comment]
> Oh, that sounds like a compatibility issue. What's your modlist?

I will send you my modlist.
![image](https://github.com/user-attachments/assets/8b517468-dbf5-4ef5-b9c7-04ed76694c28)
![image](https://github.com/user-attachments/assets/69de86a1-89a9-4b90-b3b7-f06316dbcf81)

most of the mods work fine except for the mild issue with Quark (The texture issue) and Chisels and Bits (I don't even know why but it isn't working with the Changed mod)

**Comment by cecnull1** [comment]
> 1. CPM（自定义玩家模型）支持
>    并不是那么重要，但我想看到 Goop 在非 Steve 模型上正常工作，即使它只是为 Goop 使用 RNG
> 2. Quark UI 巧合
>    我希望看到按钮移到暂停菜单的右侧，因为 Quark 的按钮重叠
> 3. 给块着色并且不为受感染的块生成新的纹理
>    这很简单但是目前我拥有的模块数量都使用了物品的纹理。
> 4. 使特殊乳胶无法通过命令召唤（对于非捐赠者），
>    当我摆弄它时，特殊乳胶使我的电脑崩溃了两次，但看到非指定的乳胶很有趣。

还有：机械动力模组按钮也重合了
Also, the buttons on the mechanical power module have overlapped

**Comment by LtxProgrammer** [comment]
Stale
