### ISSUE TITLE
Flying rubber beasts have abnormal movement speed

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#976]
我在测试的时候（2024年7月27日编译的），发现处于可以飞行的胶兽的移动速度异常。

When I was testing (compiled on July 27, 2024), I found that the movement speed of the flying rubber beast was abnormal.

我使用IBE Editor模组查看了玩家的NBT数据，发现有一个属性异常

I used the IBE Editor mod to view the player's NBT data and found an abnormal attribute

`abilities.walkSpeed: 0.01`

看样子好像是多打了一个0

It seems like an extra 0 was hit

**Comment by cecnull1** [comment]
不过，这似乎挺有趣的（0.01速度），修复后，这个Bug可以作为额外的规则添加

However, this seems quite interesting (0.01 speed), and after fixing it, this bug can be added as an additional rule

**Comment by LtxProgrammer** [comment]
Should now be fixed in df63ba95a8a09648f70849844d690fa69e9e3f05

**Comment by cecnull1** [comment]
先来个题外话：
你（LtxProgrammer）认为我是什么人？

Let's start with a digression:
Who do you (LtxProgrammer) think I am?

**Comment by LtxProgrammer** [comment]
I don't know who you are, or who you might be. Is there something I should know?

**Comment by cecnull1** [comment]
只是启发而已，你可以不回答

It's just inspiration, you don't have to answer

**Comment by LtxProgrammer** [comment]
Oh, ok. It came off as kind of hostile.
