### ISSUE TITLE
Bug in brushing items

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#979]
如果把只适用于四腿的护甲，或只适用于无腿的护甲，快速用shift+左键穿戴时（我是手速非常快的人），有一定几率会出现2个一模一样物品，而且还是真的物品，不是虚的物品。

If the armor is only applicable to four legged armor, or only applicable to legless armor, when you quickly use shift+left button to wear it (I am a person with very fast hand speed), there is a certain probability that two identical items will appear, which are real items, not virtual items.

Video:

https://github.com/user-attachments/assets/da817abe-b158-4145-a4c5-bbc5b4f90dbf

https://github.com/user-attachments/assets/18a223b3-7e00-4280-879b-314e43ae0eb2

**Comment by cecnull1** [comment]
该Bug在生存模式适用

This bug is applicable in survival mode

**Comment by LtxProgrammer** [comment]
Should be fixed in f747653603a43bcdc035b9fa5ca882550af547e9
