### ISSUE TITLE
Partial Dark Latex crashing issue.

### ISSUE THREAD

**Issue by jonjonjongamer** [LtxProgrammer/Changed-Minecraft-Mod#995]
opening the game fails constantly for me and my friends, says;

The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: No model for layer changed:dark_latex_wolf_partial#main

got a general idea why this is happening but i dont know how to fix it

**Comment by LtxProgrammer** [comment]
Please see #943. If you are in the discord, please look at the pinned message in mod-tech-support.
